### ISSUE TITLE
Error at running in isomorphic application

### ISSUE THREAD

**Issue by i1skn** [react-toolbox/react-toolbox#160] opened 2015-11-24 10:15 UTC
Hi, I'm trying to use toolbpx in isomorphic application. But have some troubles...
Here is my webpack config:
```
import path from 'path';
import webpack from 'webpack';
import merge from 'lodash.merge';

import ExtractTextPlugin from 'extract-text-webpack-plugin';

const DEBUG = !process.argv.includes('release');
const VERBOSE = process.argv.includes('verbose');
const WATCH = global.WATCH === undefined ? false : global.WATCH;
const AUTOPREFIXER_BROWSERS = [
  'Android 2.3',
  'Android >= 4',
  'Chrome >= 35',
  'Firefox >= 31',
  'Explorer >= 9',
  'iOS >= 7',
  'Opera >= 12',
  'Safari >= 7.1',
];
const GLOBALS = {
  'process.env.NODE_ENV': DEBUG ? '"development"' : '"production"',
  __DEV__: DEBUG,
};
const JS_LOADER = {
  test: /\.jsx?$/,
  include: [
    path.resolve(__dirname, '../node_modules/react-routing/src'),
    path.resolve(__dirname, '../src'),
  ],
  loader: 'babel-loader',
};

//
// Common configuration chunk to be used for both
// client-side (app.js) and server-side (server.js) bundles
// -----------------------------------------------------------------------------

const config = {
  output: {
    publicPath: '/',
    sourcePrefix: '  ',
  },

  cache: DEBUG,
  debug: DEBUG,

  stats: {
    colors: true,
    reasons: DEBUG,
    hash: VERBOSE,
    version: VERBOSE,
    timings: true,
    chunks: VERBOSE,
    chunkModules: VERBOSE,
    cached: VERBOSE,
    cachedAssets: VERBOSE,
  },

  plugins: [
    new webpack.optimize.OccurenceOrderPlugin(),
  ],

  resolve: {
    extensions: ['', '.webpack.js', '.web.js', '.js', '.jsx', '.scss'],
  },

  module: {
    loaders: [
      {
        test: /\.json$/,
        loader: 'json-loader',
      }, {
        test: /\.txt$/,
        loader: 'raw-loader',
      }, {
        test: /\.(png|jpg|jpeg|gif|svg|woff|woff2)$/,
        loader: 'url-loader?limit=10000',
      }, {
        test: /\.(eot|ttf|wav|mp3)$/,
        loader: 'file-loader',
      },
    ],
  },

  postcss: function plugins() {
    return [
      require('postcss-import')({
        onImport: files => files.forEach(this.addDependency),
      }),
      require('postcss-nested')(),
      require('postcss-cssnext')({ autoprefixer: AUTOPREFIXER_BROWSERS }),
    ];
  },
};

//
// Configuration for the client-side bundle (app.js)
// -----------------------------------------------------------------------------

const appConfig = merge({}, config, {
  entry: [
    ...(WATCH ? ['webpack-hot-middleware/client'] : []),
    './src/app.js',
  ],
  output: {
    path: path.join(__dirname, '../build/public'),
    filename: 'app.js',
  },

  // Choose a developer tool to enhance debugging
  // http://webpack.github.io/docs/configuration.html#devtool
  devtool: DEBUG ? 'cheap-module-eval-source-map' : false,
  plugins: [
    ...config.plugins,
    new ExtractTextPlugin('app.css'),
    new webpack.DefinePlugin(GLOBALS),
    ...(!DEBUG ? [
      new webpack.optimize.DedupePlugin(),
      new webpack.optimize.UglifyJsPlugin({
        compress: {
          warnings: VERBOSE,
        },
      }),
      new webpack.optimize.AggressiveMergingPlugin(),
    ] : []),
    ...(WATCH ? [
      new webpack.HotModuleReplacementPlugin(),
      new webpack.NoErrorsPlugin(),
    ] : []),
  ],
  module: {
    loaders: [
      WATCH ? {
        ...JS_LOADER,
        query: {
          // Wraps all React components into arbitrary transforms
          // https://github.com/gaearon/babel-plugin-react-transform
          plugins: ['react-transform'],
          extra: {
            'react-transform': {
              transforms: [
                {
                  transform: 'react-transform-hmr',
                  imports: ['react'],
                  locals: ['module'],
                }, {
                  transform: 'react-transform-catch-errors',
                  imports: ['react', 'redbox-react'],
                },
              ],
            },
          },
        },
      } : JS_LOADER,
      ...config.module.loaders,
      {
        test: /(\.scss|\.css)$/,
        loader: ExtractTextPlugin.extract('style', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap'),
      },
    ],
  },
});

//
// Configuration for the server-side bundle (server.js)
// -----------------------------------------------------------------------------

const serverConfig = merge({}, config, {
  entry: './src/server.js',
  output: {
    path: './build',
    filename: 'server.js',
    libraryTarget: 'commonjs2',
  },
  target: 'node',
  externals: [
    function filter(context, request, cb) {
      const isExternal =
        request.match(/^[a-z][a-z\/\.\-0-9]*$/i) &&
        !request.match(/^react-routing/) &&
        !context.match(/[\\/]react-routing/);
      cb(null, Boolean(isExternal));
    },
  ],
  node: {
    console: false,
    global: false,
    process: false,
    Buffer: false,
    __filename: false,
    __dirname: false,
  },
  devtool: 'source-map',
  plugins: [
    ...config.plugins,
    new webpack.DefinePlugin(GLOBALS),
    new webpack.BannerPlugin('require("source-map-support").install();',
      { raw: true, entryOnly: false }),
  ],
  module: {
    loaders: [
      JS_LOADER,
      ...config.module.loaders,
      {
        test: /(\.scss|\.css)$/,
        loader: 'css/locals?module&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap',
      },
    ],
  },
});

export default [appConfig, serverConfig];
```
Actually building of bundle is done without errors, but when I try to run server.js - I get error:
```
Error: Cannot find module './style'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/some-path/node_modules/react-toolbox/lib/font_icon/index.js:15:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```
In my server.js I do not using hot-middleware.

**Comment by nathanmarks** [comment] 2015-11-24 13:33
Right now the files are calling css without an extension so you need to have `scss` resolve automatically as a module extension in webpack.

@javivelasco @soyjavi I encountered this myself, a significant number of people don't auto-resolve their scss/css extensions as modules and the `.scss` in the `import` statement is more expressive. Thoughts?

**Comment by asynxis** [comment] 2015-11-24 16:59
Actually I found solution, but here is another problem. When I add react-toolbox stuff to server.js - it loads whole dependency list into it. Is anybody use already react-toolbox in iso applications?

**Comment by javivelasco** [comment] 2015-11-24 17:32
@asynxis that's a big issue. Please tell us details if you can't get it working properly

**Comment by asynxis** [comment] 2015-11-24 18:55
I've added u in repo, when pull. install, start. It pack whole react-toolbox in build/server.js. And size of it become 700+kb and hot reload can take up to 15 sec...

**Comment by nathanmarks** [comment] 2015-11-24 22:10
@asynxis 

Can you add me to the repo?

**Comment by asynxis** [comment] 2015-11-24 22:11
Done!

**Comment by nathanmarks** [comment] 2015-11-24 23:53
@asynxis Which repo? I'm seeing "This repository is empty." for the react isomorphic boilerplate.

**Comment by asynxis** [comment] 2015-11-25 00:26
https://github.com/asynxis/uma-e3-summit.org

**Comment by nathanmarks** [comment] 2015-11-25 14:12
@asynxis Thanks, I'll try take a look this evening

**Comment by asynxis** [comment] 2015-11-25 14:14
@nathanmarks thanks!

**Comment by nathanmarks** [comment] 2015-11-28 00:30
@asynxis Just letting you know I haven't forgotten this -- had a very busy week at work

**Comment by javivelasco** [comment] 2015-12-11 18:23
Is it a bug? Did you get it resolved? If so, I'd like to close the issue to reduce noise.
Thanks!

**Comment by nocon** [comment] 2015-12-12 20:36
I'm facing the same issue - isomorphic app with both dev and hot middleware on.

**Comment by nathanmarks** [comment] 2015-12-12 21:09
@nocon is it the same setup? As in creating a server side bundle?

Forgive me for my ignorance as I don't use a bundle for my server side stuff (you can still leverage webpack using webpack isomorphic tools) but isn't the idea of a bundle that the dependencies get bundled up too?

I don't bundle my node apps so I'm not sure what the intended outcome is. Are you importing react toolbox in its entirety or are you importing modules directly from the components or lib folders?

**Comment by nathanmarks** [comment] 2015-12-12 21:12
I guess what I'm asking is when creating a server side node bundle, what should and shouldnt be in there? The idea of bundling the server app is foreign to me. I just use webpack-isomorphic-tools to get webpack goodies on the server

**Comment by nocon** [comment] 2015-12-12 21:16
Hmm, I think I only use bundling for the client side, but I'm not sure. I've started working with React only recently, and have been following some isomorphic app tutorials. Here's my server.js: 

```
import express                   from 'express';
import React                     from 'react';
import { renderToString }        from 'react-dom/server'
import { RoutingContext, match } from 'react-router';
import createLocation            from 'history/lib/createLocation';
import routes                    from 'routes';
import { Provider }              from 'react-redux';
import * as reducers             from 'reducers';
import promiseMiddleware         from 'lib/promiseMiddleware';
import fetchComponentData        from 'lib/fetchComponentData';
import { createStore,
         combineReducers,
         applyMiddleware }       from 'redux';
import path                      from 'path';
import webpackDev                from './webpack.dev';
import injectTapEventPlugin from 'react-tap-event-plugin';

const app = express();

if (process.env.NODE_ENV !== 'production') webpackDev(app);
else app.use(express.static(path.join(__dirname, 'dist')));

app.use( (req, res) => {
  const location = createLocation(req.url);
  const reducer  = combineReducers(reducers);
  const store    = applyMiddleware(promiseMiddleware)(createStore)(reducer);
  
  match({ routes, location }, (err, redirectLocation, renderProps) => {
    if(err) {
      console.error(err);
      return res.status(500).end('Internal server error');
    }

    if(!renderProps)
      return res.status(404).end('Not found');

    function renderView() {
      delete process.env.BROWSER;
      
      const InitialView = (
        <Provider store={store}>
          <RoutingContext {...renderProps} />
        </Provider>
      );

      const componentHTML = renderToString(InitialView);
      const initialState = store.getState();
      const HTML = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>Work title</title>
          <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
          <link href="/bundle.css" rel="stylesheet">
          <script>
            window.__INITIAL_STATE__ = ${JSON.stringify(initialState)};
          </script>
        </head>
        <body>
          <div id="react-view">${componentHTML}</div>
          <script type="application/javascript" src="/bundle.js"></script>
        </body>
      </html>
      `;

      return HTML;
    }

    fetchComponentData(store.dispatch, renderProps.components, renderProps.params)
      .then(renderView)
      .then(html => res.end(html))
      .catch(err => res.end(err.message));
  });
});

export default app;
```

**Comment by nathanmarks** [comment] 2015-12-13 04:08
@nocon Sorry, I was replying on my phone and mixed this up with another issue related to server side use!

Ignore what I said about the bundle -- not relevant for this thread.

What's the exact issue you're having? is it the style issue?

**Comment by nocon** [comment] 2015-12-13 11:40
Yes, it's the style issue: 

```
Error: Cannot find module './style'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/some-path/node_modules/react-toolbox/lib/font_icon/index.js:15:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Now, I did manage to fix it by switching to [this boilerplate] (https://github.com/erikras/react-redux-universal-hot-example). I can only assume the issue was caused by wrong webpack config or lack of some library (webpack-isomorphic-tools maybe?)

**Comment by nocon** [comment] 2015-12-13 14:43
Actually, I'm still getting style issue, even with the new boilerplate. App, Slider, Autocomplete throw an exception on render: `Cannot read property 'root' of undefined` (undefined being the style object imported from './style'). Input and Dropdown don't, but they are not working correctly anyway - Input floating label overlaps value box, and dropdown doesn't expand at all.

**Comment by nathanmarks** [comment] 2015-12-13 20:09
@nocon Yeah, your webpack config may have been funky. I saw you had a `webpack.dev.js` file being imported but without seeing it I had no idea what it was doing.

**Comment by nickw** [comment] 2015-12-30 16:05
> Actually I found solution, but here is another problem.

@asynxis Can you share what the solution was to your initial issue? I'm having the same exact problem, my server code builds fine, but when I try to run it I get the `Error: Cannot find module './style'` in the `App` component. I have the correct `resolve.extensions` config.

**Comment by SimonSelg** [comment] 2015-12-30 16:18
Could you please post the whole error message so we can check if it's looking in the correct folder?

Normally the solution should be to use something like this:

```js
resolve: {
    root: paths.base(config.dir_client),
    extensions: ['', '.js', '.jsx', '.scss']
  },
```

the important part is the `.scss`.

**Comment by nickw** [comment] 2015-12-30 16:19
Here's the relevant part of my webpack config:

```
resolve: {
    extensions: ['', '.js', '.jsx', '.scss'],
    modulesDirectories: [
      'node_modules',
      path.join(__dirname, '..', '/node_modules')
    ],
  },
```

And the error I'm getting when running the Node server:
```
Error: Cannot find module './style'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/nickwientge/Desktop/universal-react/node_modules/react-toolbox/lib/app/App.js:13:14)
    at Module._compile (module.js:434:26)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/nickwientge/Desktop/universal-react/node_modules/babel-cli/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by nickw** [comment] 2015-12-30 16:54
@SimonSelg @asynxis I found the solution to my issue. 

I'm following [these posts](http://jlongster.com/Backend-Apps-with-Webpack--Part-I) for building my server side code with Webpack. The instructions have you add all the node_modules to Webpack's `externals` config:

```
const nodeModules = {};
fs.readdirSync('node_modules').filter((x) => {
  return ['.bin'].indexOf(x) === -1;
}).forEach((mod) => {
  nodeModules[mod] = 'commonjs ' + mod;
});
```

Which means `react-toolbox` is not being bundled with the built code. As a temporary solution I've added `delete nodeModules['react-toolbox'];` after these lines and things are working fine so far.

**Comment by javivelasco** [comment] 2015-12-31 01:40
Well, truth is I didn't try toolbox yet with server side rendering.
I'll try to create an example next week. Also, feel free to open a PR in the example repo for server side rendering if you want!

**Comment by FoxxMD** [comment] 2016-01-08 19:28
I'm seeing the same issue with style, also using [universal-hot-example boilerplate](https://github.com/erikras/react-redux-universal-hot-example)

```
==> 🚧  Webpack development server listening on port 3001
[webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/ripple/style.scss
[webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/checkbox/style.scss
[piping] can't execute file: /app/bin/server.js
[piping] error given was: TypeError: Cannot read property 'ripple' of undefined
	 at Object.<anonymous> (/app/node_modules/react-toolbox/lib/checkbox/Check.js:42:32)
	 at Module._compile (module.js:425:26)
	 at Module._extensions..js (module.js:432:10)
	 at require.extensions.(anonymous function) (/app/node_modules/babel-core/lib/api/register/node.js:214:7)
	 at Object._module3.default._extensions.(anonymous function) [as .js] (/app/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:250:71)
	 at Module.load (module.js:356:32)
	 at Module._load (module.js:313:12)
	 at Function.module._load (/app/node_modules/piping/lib/launcher.js:32:16)
	 at Module.require (module.js:366:17)
	 at require (module.js:385:17)
[piping] further repeats of this error will be suppressed...
[webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/ripple/style.scss
[webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/checkbox/style.scss
[webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/ripple/style.scss
[webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/checkbox/style.scss
[webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/ripple/style.scss
```

**Comment by javivelasco** [comment] 2016-01-08 22:36
That project is using [webpack isomorphic tools](https://github.com/halt-hammerzeit/webpack-isomorphic-tools) and probably they don't have configure by default the inclusion of CSS modules files from `node_modules`.

The way to solve this is to make sure they are doing it. An alternative to webpack isomorphic tools would be to use the [require hook](https://github.com/css-modules/css-modules-require-hook)

**Comment by 1mjwebbthew** [comment] 2016-02-20 22:10
i believe your implementation of `material design` to be the cleanest to date. /bow

a possible solution here for integrating with what i believe to be the 'best' `redux` implementations to date:

https://github.com/erikras/react-redux-universal-hot-example

becomes:

https://github.com/bdefore/universal-redux

becomes:

https://github.com/bdefore/universal-redux-starter

with:

https://github.com/bdefore/universal-redux#customization

and in a new, `config` folder at the root of `universal-redux-starter` clone,
add the file: universal-redux.config.js

e.g. config/universal-redux.config.js

perhaps using the stencil:
https://github.com/bdefore/universal-redux/blob/master/config/universal-redux.config.js#L231

one can add the following `resolve` object :

  resolve: {
    extensions: ['.scss' ]
  }

e.g. a total `config/universal-redux.config.js` file description:

module.exports = {
  webpack: {
    config: {
      resolve: {
        extensions: ['.scss' ]
      }
    }
  }
};


cmd line:
^C
npm run dev

humanly:
rejoice

P.S. this solution makes sense at:
    "react-addons-css-transition-group": "^0.14.7",
    "react-toolbox": "^0.14.1",
    "universal-redux": "3.0.0-rc30"
    "react": "^0.14.6",
    "react-dom": "^0.14.6",
    "react-redux": "4.3.0",
    "react-router": "2.0.0",
    "react-router-redux": "3.0.0"

  /deep thanks to the project and library owners

**Closed** 2016-07-10 15:43 UTC
Labels: bug, enhancement
