### ISSUE TITLE
JSPM

### ISSUE THREAD

**Issue by giltig** [react-toolbox/react-toolbox#82] opened 2015-11-09 09:38 UTC
Hi,
right now there's only support for webpack.
using your great library with jspm is very inconvenient because you need to build the library all the time instead of using it raw.
Can you please add support for jspm

**Comment by javivelasco** [comment] 2015-11-10 00:15
Hi, thanks for your words :)

I would like to support other module loaders such as JSPM or browserify since there is already an example implementation with CSS modules. I never used JSPM before so help here is really appreciated. Let's see if somebody can help with it.

Thanks!

**Comment by shidhincr** [comment] 2015-11-10 06:32
@javivelasco I would like to pick this up. Let me try how I can do this.

**Comment by javivelasco** [comment] 2015-11-10 10:15
Thanks sounds awesome! Thanks!! :)

**Comment by rockneverdies55** [comment] 2015-11-20 15:46
+1 for browserify integration...

**Comment by bali182** [comment] 2015-11-23 20:45
+1 for jspm! I started learning it around a week ago, but if nobody started it, I will give the jspm integration a shot, because this looks like THE material library for react, and it would be a shame to leave out poor jspm ;) Btw guys, really good job, it's rare, that I look at a library, and the structure & code just looks clear.

**Comment by bali182** [comment] 2015-11-23 21:26
There will be problems with the sass. The best looking sass-plugin I found is this: https://github.com/mobilexag/plugin-sass , but it requires to load the `.scss` files like this: `import './style.scss!'` (notice the `.scss!`). And even when doing `import style from './style.scss!'` it just appends the contents of the compiled `.scss` to the documents head, and the `style` object is empty. This needs some serious work.

**Comment by shidhincr** [comment] 2015-11-24 05:40
@bali182 I was trying to implement the JSPM version, but as you said the sass files loading is pretty difficult. JSPM requires non-js files to be imported with `!` at the end of the file name.

I was thinking about keeping a separate build for JSPM, by re-writing these imports using a gulp task. I am not sure if that's the right approach.

**Comment by bali182** [comment] 2015-11-24 06:55
Damn, sorry, looking back I see now, that you are working on it as well. Last night I was going through how webpack is doing this, and how jspm is, but it's still a bit unclear, if the `./filename.extension!` style import is hardcoded in jspm for non js imports? Or is there a chance, that we could hack together a custom sass loader plugin, which is capable of handling the existing import formats? That sounds (in my opinion at least) a bit safer, than doing the import replaces in gulp. Maybe I'm wrong, since that would require to somehow take over the loading if for example `./style.js` is not found...

**Comment by shidhincr** [comment] 2015-11-24 07:29
@bali182 I think the challenge here is not only `!` in the file name imports, the file name extentions also missing. Webpack handles this well, but I guess JSPM assumes this as a JS module.

A custom sass loader plugin seems a good option.

**Comment by javivelasco** [comment] 2015-11-24 08:49
Now I think we have some files that are required with the extension but they should be removed since webpack figures it out. I'm sorry I can't help, I don't have experience con JSPM, but it's great to see movement around it!

Thanks guys!

**Comment by bali182** [comment] 2015-11-24 10:38
@shidhincr I found a guide, which partially explain, what we want to do: https://github.com/systemjs/systemjs/blob/master/docs/creating-plugins.md

We can hook into `locate` (locate the sass files - hopefully we can get around the `.scss!` stuff here), then maybe also hook into `translate`, where we can just take the compiled scss result, and return in the same json object format as the webpack plugin does. I try it after work! Big question: do people use jspm without System.js (with something else)? I think the default css plugin only supports System.js as well.

@javivelasco I really hope, we can do this, I really would like to use it. :)

**Comment by javivelasco** [comment] 2015-11-24 11:00
I hope soo too @bali182 !

**Comment by shidhincr** [comment] 2015-11-24 13:36
@javivelasco  @bali182  Awesome !! Thanks for the link.

Regarding SystemJS, I don't think that anyone is using JSPM without systemjs. So, IMO, its safe.

**Comment by bali182** [comment] 2015-11-24 18:46
Well, I was looking up, what exactly does `!` stuff mean, and according to this [SO question](http://stackoverflow.com/questions/31620018/es6-imports-what-does-the-exclamation-mark-mean):

```
import foo from `foo.css!` // is a shortcut for
import foo from `foo.css!css` // where the part after the ! is the plugin name, that handles the loading
``` 

It looks pretty clean, but if this is correct, I have no idea, how could we activate a custom loader plugin. I asked about it in the System.js issue section, hopefully we get some help: https://github.com/systemjs/systemjs/issues/930

**Comment by giltig** [comment] 2015-12-01 14:09
Hi, apparently there is a stable sass plugin for jspm :
https://github.com/mobilexag/plugin-sass

**Comment by shidhincr** [comment] 2015-12-01 16:00
@giltig I did have a look at the plugin-sass. But, the plugin also require us to write the import statement with `!`.

**Comment by elie222** [comment] 2015-12-01 22:56
+1 for browserify

**Comment by giltig** [comment] 2015-12-09 13:24
any news with that?

**Comment by javivelasco** [comment] 2015-12-09 14:16
I would like to create an example with browserify for now. For the JSPM, as the issue is labeled, I would like to get some help since I have no experience with it.

**Comment by praneybehl** [comment] 2015-12-10 13:04
+1 for browserify

**Comment by omerts** [comment] 2015-12-21 19:37
@shidhincr @bali182  Any updates with JSPM integration?

**Comment by shidhincr** [comment] 2015-12-28 07:56
@omerts I couldn't figure out a proper solution for this. I would leave this to others if anyone need to pick it up. Meantime, I'll have to experiment with  JSPM more.

**Comment by naptiv** [comment] 2016-01-19 09:26
+1 for browserify

**Comment by smilyanp** [comment] 2016-02-13 14:14
+1 for browserify

**Comment by etnbrd** [comment] 2016-04-22 09:31
I found a solution for JSPM :

+ Install sass plugin to handle .scss files.
I guess that the scss=sass means that the sass plugin will handle scss files.
```
jspm install scss=sass
```
+ Create a `style.js` file in `lib/*` with only one line :
```
import './style.scss!';
```

But it lead to another problem, which is the impossibility for [plugin-sass](url) to use imports inside conditionals.
And it seems to be Sass default, see : [#451](https://github.com/sass/sass/issues/451). So I am wondering, @javivelasco, what is the sass library you are using ?

It seems that the good practice is to import a mixin, and conditionnaly include the mixin, like [this](http://stackoverflow.com/a/13879344/933670) : 
_partial.scss
```
@mixin partial {
    .test { color: red }
    // other styles here
}
```
styles.scss
```
@import "partial";
@if $someval == true {
    @include partial;
}
```

**Comment by etnbrd** [comment] 2016-04-22 09:57
I didn't thought this through. Typical me :p
Making a partial with all the color palette variables simply encapsulates them in an unreachable scope.

Instead, I applied [this quick fix](https://github.com/react-toolbox/react-toolbox/issues/466#issuecomment-212887893)

**Comment by javivelasco** [comment] 2016-07-10 15:41
I'm closing since there is already people that made it work with JSPM!

**Closed by javivelasco** 2016-07-10 15:41 UTC
Labels: help wanted

**Comment by alexeychikk** [comment] 2017-08-14 18:11
@javivelasco Im getting
```
err  SyntaxError: jspm_packages/npm/react-toolbox@2.0.0-beta.12/lib/autocomplete/theme.css: Unexpected token (1:0)
> 1 | :root {
    | ^
  2 |   --palette-red-50: rgb(255, 235, 238);
  3 |   --palette-red-100: rgb(255, 205, 210);
  4 |   --palette-red-200: rgb(239, 154, 154);
    at Parser.pp$5.raise (C:\Git\agile-engine-task\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (C:\Git\agile-engine-task\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp$3.parseExprAtom (C:\Git\agile-engine-task\node_modules\babylon\lib\index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (C:\Git\agile-engine-task\node_modules\babylon\lib\index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (C:\Git\agile-engine-task\node_modules\babylon\lib\index.js:3474:19)
    at Parser.pp$3.parseExprOps (C:\Git\agile-engine-task\node_modules\babylon\lib\index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (C:\Git\agile-engine-task\node_modules\babylon\lib\index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (C:\Git\agile-engine-task\node_modules\babylon\lib\index.js:3344:19)
    at Parser.pp$3.parseExpression (C:\Git\agile-engine-task\node_modules\babylon\lib\index.js:3306:19)
    at Parser.pp$1.parseStatement (C:\Git\agile-engine-task\node_modules\babylon\lib\index.js:1906:19)
    at Parser.pp$1.parseBlockBody (C:\Git\agile-engine-task\node_modules\babylon\lib\index.js:2268:21)
    at Parser.pp$1.parseTopLevel (C:\Git\agile-engine-task\node_modules\babylon\lib\index.js:1778:8)
    at Parser.parse (C:\Git\agile-engine-task\node_modules\babylon\lib\index.js:1673:17)
    at parse (C:\Git\agile-engine-task\node_modules\babylon\lib\index.js:7246:37)
    at File.parse (C:\Git\agile-engine-task\node_modules\babel-core\lib\transformation\file\index.js:517:15)
    at File.parseCode (C:\Git\agile-engine-task\node_modules\babel-core\lib\transformation\file\index.js:602:20)
```
Any ideas please?

**Comment by javivelasco** [comment] 2017-09-01 14:35
Sounds like jspm is not well configured since it's trying to parse the PostCSS module as something else, that's why you're getting an error. I know nothing about JSPM so I can't really help too much, sorry :(
