### ISSUE TITLE
Drawer content under fixed AppBar - OK if AppBar is not fixed

### ISSUE THREAD

**Issue by genyded** [react-toolbox/react-toolbox#516] opened 2016-05-15 22:34 UTC
I copied the following from the samples...

<details>
<summary>Sample Code</summary>
```js
...
    return (
      <div>
        <Layout>
           <NavDrawer active={this.state.drawerActive}
               pinned={this.state.drawerPinned} permanentAt='xxxl'
               onOverlayClick={ this.toggleDrawerActive }>
               <p style={{color: 'red'}}>
                   Navigation, account switcher, etc. go here.
               </p>
           </NavDrawer>
           <Panel>
               <AppBar fixed={true}>
                 <IconButton icon='menu' inverse={ true } onClick={ this.toggleDrawerActive }/>
                 {icon}
               </AppBar>
               <div style={{ flex: 1, overflowY: 'auto', padding: '1.8rem' }}>
                 <h1>Main Content</h1>
                 <p>Main content goes here.</p>
                 <Checkbox label='Pin drawer' checked={this.state.drawerPinned} onChange={this.toggleDrawerPinned} />
                 <Checkbox label='Show sidebar' checked={this.state.sidebarPinned} onChange={this.toggleSidebar} />
                 <h1>{app.test}</h1>
                 {children}
               </div>
           </Panel>
           <Sidebar pinned={ this.state.sidebarPinned } width={ 5 }>
               <div><IconButton icon='close' onClick={ this.toggleSidebar }/></div>
               <div style={{ flex: 1 }}>
                   <p>Supplemental content goes here.</p>
               </div>
           </Sidebar>
         </Layout>
      </div>
    )
...
```
</details>

... and if the AppBar is not fixed, the top drawer content is OK..

<details>
<summary>Screenshot without fixed AppBar</summary>
![image](https://cloud.githubusercontent.com/assets/3081676/15277219/2129a45a-1ac3-11e6-923b-4f63090ac705.png)
</details>

...but if I set the AppBar to `fixed={true}` then the top drawer content is under the AppBar...

<details>
<summary>Screenshot with fixed AppBar</summary>
![image](https://cloud.githubusercontent.com/assets/3081676/15277150/1e78d3e0-1ac1-11e6-8052-d50e1f9985aa.png)
</details>

**React Toolbox Version:** 0.16.2

**Comment by genyded** [comment] 2016-05-15 23:07
OK - Apparently this should use Drawer now instead of NavDrawer, but the playground sample still has NavDrawer so I guess that's the real issue?

**Comment by carlitux** [comment] 2016-06-10 03:31
I found an ugly solution

```scss
[data-react-toolbox=nav-drawer-scrim] {
  z-index: 301 !important;
}
```

fixed property on AppBar sets the z-index to 300 and also the div that wraps the NavDrawer is also z-index to 300 the AppBar is on top.

**Comment by RyuuGan** [comment] 2016-06-14 14:48
@carlitux It doesn't help if you are also using `pinnedAt` or `pinned` option. It now goes upon appbar but not side by side.

**Comment by carlitux** [comment] 2016-06-14 18:54
@RyuuGan maybe you have to customise when those options are set... they add other class names.

**Comment by javivelasco** [comment] 2016-06-16 19:23
I don't know if I misunderstood the issue but you should not confuse the `Drawer` and `NavDrawer`. Although both are visually similar, one is intended to display content that may vary and the other one is intended for a fixed navigation sidebar that is displayed depending on the screen size.

Although the posted solution is not beautiful (avoid important!) you can also assign a classname to boost priority and customize the z-index level.

**Comment by carlitux** [comment] 2016-06-16 19:45
@javivelasco the issue is NavDrawer don't work same way when AppBar is fixed or not... when fixed NavDrawer is behind the AppBar and when is not fixed goes in front of it.

Yes is not beautiful use the important keyword but I couldn't find a way to avoid that using classname.

**Comment by javivelasco** [comment] 2016-06-16 21:32
Gonna give a look during the weekend! :)

**Comment by patrick-jones** [comment] 2016-06-20 14:22
It is not necessary to use fixed on the navbar when using `Layout`.  Let flexbox take care of it for you:

- `Layout` should be inside of a block that defines the space you want to allocate to it. Often this is the full height and width of the window.
- Add your 'Layout` with your `NavDrawer` and a `Panel` with `scrollY` equal to `false`. This will keep the app bar in a fixed position.
- Inside the `Panel`, add your `AppBar` (*without* `fixed`).  Below that, add a `div` with the attributes `flex: 1; overflow-y: auto`
- Your content goes inside that last `div`

Here is [an example](https://output.jsbin.com/yurugomime).  It does not use React Toolkit directly but it uses the same CSS techniques.

**Comment by carlitux** [comment] 2016-06-20 18:52
@patrick-jones thanks 

Also I found this if anyone wants to try http://codepen.io/anthonyLukes/pen/DLBeE just adding classNames AppBar and the div where will go the content I am using this:

```scss
.layout {  // this class should go in div that wraps Layout component, maybe rename as '.app'
  position: absolute;

  .content {  // where content go
    flex: 1 1 auto;
    overflow-y: auto;
    position: relative; // need this to position inner content
    width: 100%;
  }

  .header {  // the appbar
    flex: 0 0 auto;
  }
}
```

And JSX as @patrick-jones described removing scrollY equal to false and also removing the fixed prop on AppBar

**Comment by javivelasco** [comment] 2016-06-25 10:53
Can this be closed then?

**Closed** 2016-07-10 15:32 UTC
