### ISSUE TITLE
Cannot resolve 'file' or 'directory' ./style

### ISSUE THREAD

**Issue by Light1c3** [react-toolbox/react-toolbox#508] opened 2016-05-07 14:04 UTC
I'm using the React-Starter-Kit and I'm attempting to add React-Toolbox to it for the Navigation, but I keep running into this error whenever I attempt to import something in.

`ERROR in ./~/react-toolbox/lib/button/Button.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ./style in C:\Users\light1c3\Documents\GitHub\ResumeSite\node_modules\react-toolbox\lib\button
     @ ./~/react-toolbox/lib/button/Button.js 28:13-31`

**Comment by felipeleusin** [comment] 2016-05-07 14:48
do you have a scss loader enabled?

**Comment by klummy** [comment] 2016-05-07 15:54
Hi @felipeleusin, I am also getting a similar error and I have a SCSS loader enabled. Here is how my webpack module looks like in my webpack.config.js file:

```
  module: {
    loaders: [
      {
        test: /(\.js|\.jsx)$/,
        loaders: ['react-hot', 'babel'],
        exclude: /node_modules/,
      }, {
        test: /(\.scss|\.css)$/,
        loader: ["style", "css", "sass"]
      }
    ]
  },
```

**Comment by felipeleusin** [comment] 2016-05-07 16:00
Can you try using ?modules to the css loader?

```
loader: ["style", "css?modules", "sass"]
```
should do the trick

**Comment by Light1c3** [comment] 2016-05-07 21:29
I'll give that a shot and update the post once I've tried it.

**Comment by Light1c3** [comment] 2016-05-07 21:32
I can't find that section in my webpack.config.js. Where should I insert the code?

**Comment by xomyaq** [comment] 2016-05-08 14:20
This is how styles are imported in components, e.g. in [IconButton.js](https://github.com/react-toolbox/react-toolbox/blob/dev/components/button/IconButton.js#L5)
`
import style from './style';
`
Webpack can't find proper loader for file without extension, that cause an error

**Comment by simofacc** [comment] 2016-05-09 09:57
Hi, is there any fix for this yet? I am trying to check if it's possible to import relative files and resolve their extension.

**Comment by xomyaq** [comment] 2016-05-09 10:20
Sorry @simofacc I was mistaken. It's not a bug of React Toolbox.

You need add a few lines to your Webpack config:
0. install dependencies `npm install --save-dev node-sass@3.4.2 sass-loader` _(it's important to install version 3.4.2 of node-sass—[look here](https://github.com/react-toolbox/react-toolbox/issues/466) for more details)_;
1. add `.scss` extension to resolve section [like here](https://github.com/react-toolbox/react-toolbox-example/blob/master/webpack.config.js#L19);
2. then, [add new loader](https://github.com/react-toolbox/react-toolbox-example/blob/master/webpack.config.js#L34-L37) _(toolbox-loader isn't necessary)_.

I hope this will help.

**Comment by simofacc** [comment] 2016-05-09 10:22
@xomyaq That is what I am trying to do. I installed node-sass@3.4.2 but I got a different error
```
ERROR in ./~/react-toolbox/lib/dropdown/style.scss
Module build failed: ReferenceError: window is not defined
```

**Comment by simofacc** [comment] 2016-05-09 10:26
I also keep on getting

`
    ERROR in ./~/css-loader?sourceMap&modules!./~/react-toolbox/lib/input/style.scss
    Module not found: Error: Cannot resolve 'file' or 'directory' ../base in /Applications/AMPPS/www/iGame/node_modules/react-toolbox/lib/input
     @ ./~/css-loader?sourceMap&modules!./~/react-toolbox/lib/input/style.scss 3:10-79
`

**Comment by waxmihs2902** [comment] 2016-05-09 10:30
thanks. will follow

**Comment by bernhardw** [comment] 2016-05-09 14:47
@simofacc and @Light1c3 Show us your full Webpack config or at least the part around `resolve`. Your errors may be caused by (missing) [`resolve.modulesDirectories`](https://github.com/react-toolbox/react-toolbox-example/blob/master/webpack.config.js#L20-22).

**Comment by simofacc** [comment] 2016-05-09 20:49
@bernhardw I managed to fix my issues. Had to remove node-sass first and then reinstall node-sass@3.4.2 then I had to install some other packages like sass-loader and toolbox-loader.

I also added the resolve to the configuration too.

**Comment by aviadhahami** [comment] 2016-05-13 15:58
Got the same error.

An idea:
Why not release this module with the scss files already after being processed into css? 
If this isn't possible - can we add that into the readme?

**Comment by javivelasco** [comment] 2016-05-14 10:49
It´s not possible because in that fancy you are not able to customize the style with SASS variables.

**Comment by aviadhahami** [comment] 2016-05-14 10:53
@javivelasco understandable.
From last night's experience - I've ran into too many issues installing the `react-toolbox` (all of them regarding the styling) causing me to drop it just for the sake of delivering what I needed.

Will keep track :+1:

**Comment by klummy** [comment] 2016-05-14 21:39
@aviadhahami Note - one thing that caused an issue for me was excluding the ```node_modules``` folder in my css/sass loader.

**Comment by javivelasco** [comment] 2016-05-15 11:49
@aviadhahami it will be solved with #498 hopefully. Check please

**Comment by shashank734** [comment] 2016-05-19 12:40
@simofacc can you please share your webpack.config.js ..

How you made resolve entry and module entry .. in react-starter-kit

**Comment by Natanael1234** [comment] 2016-05-28 00:40
**"You need add a few lines to your Webpack config:
0. install dependencies npm install --save-dev node-sass@3.4.2 sass-loader (it's important to install version 3.4.2 of node-sass—look here for more details);
1. add .scss extension to resolve section like here;
2. then, add new loader (toolbox-loader isn't necessary)."**

It must be --save-dev node-sass@3.4.2?

When I do it a lot of errors includind an ask to instal Python2 and VisualStudio2013...

**Closed** 2016-06-19 19:25 UTC

**Comment by coljung** [comment] 2016-08-16 22:12
So, im running into this issue as well, pretty sure its my webpack config.

This is that I already had a CSS loader but not sure how to integrate with this one. This is my current file:

`resolve: {
        extensions: ['', '.js', '.jsx','.scss'],
    },
    module: {
        preLoaders: [
            {
                test: /\.jsx?$/,
                exclude: /(node_modules|bower_components)/,
                loaders: ['eslint-loader'],
            },
        ],
        loaders: [
            {
                test: /\.jsx?$/,
                exclude: /(node_modules|bower_components)/,
                loader: 'babel-loader',
                query: {
                    presets: ['react', 'es2015', 'stage-0'],
                    plugins: [
                        'react-html-attrs',
                        'transform-class-properties',
                        'transform-decorators-legacy',
                    ],
                },
            },
            {
                test: /\.css$/,
                loaders: [
                    'style?sourceMap',
                    'css?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]',
                ],
            },
            {
                test: /\.json$/,
                loader: 'json-loader',
            },
            {
                test: /\.scss$/,
                loaders: ["style", "css", "sass"]
            }
        ],`

Thanks in advance!

**Comment by javivelasco** [comment] 2016-08-21 17:15
Check the SCSS loader configuration. You are not including `modules` option to enable CSS Modules!
