### ISSUE TITLE
Strange styling issue

### ISSUE THREAD

**Issue by digipi** [react-toolbox/react-toolbox#467] opened 2016-04-21 12:35 UTC
http://i.imgur.com/0wHEsle.png

Menu ul seems to have margin-top effecting the layout (example has margin but it's ignored).

HR has no border-top.

Removed all styles on project and still seems to be an issue.

Anyone been able to reproduce or is this just me?

**Comment by javivelasco** [comment] 2016-04-27 18:12
Weird! Gonna try to reproduce during the weekend

**Comment by javivelasco** [comment] 2017-01-23 09:05
Closing since I cannot reproduce so I guess it should work

**Closed** 2017-01-23 09:05 UTC
