### ISSUE TITLE
Cannot resolve file './style' in ./node_modules/react-toolbox/lib/link

### ISSUE THREAD

**Issue by natac13** [react-toolbox/react-toolbox#234] opened 2015-12-24 00:12 UTC
I just found react-toolbox so this maybe just me not having something setup right. However when I run webpack I get this error.
![toolbox-error](https://cloud.githubusercontent.com/assets/10660283/11987187/a82b7f82-a9a8-11e5-9907-a852152f4822.png)

Webpack file
![toolbox-webpack](https://cloud.githubusercontent.com/assets/10660283/11987201/d71366a2-a9a8-11e5-948d-2eca58674a11.png)

Dependencies.
![toolbox-depencies](https://cloud.githubusercontent.com/assets/10660283/11987205/e39ecd80-a9a8-11e5-8fd3-e0629ea38578.png)

I have tired removing the node_module exclude part. Removing the include on the style loaders. Still the same issue. I have found nothing by searching google. So submitting an issue

P.S I have also tried other components. And even import the source version to have my webpack transpile but still the same

**Comment by Bartekus** [comment] 2015-12-24 08:08
I've fixed everything and submitted the pull request so if you like you can grab that as everything is up to date, working and tested ok.

**Comment by javivelasco** [comment] 2015-12-24 13:56
Alright, I'll check there. Closing.
Thanks!

**Closed by javivelasco** 2015-12-24 13:56 UTC

**Comment by natac13** [comment] 2015-12-24 20:09
@Bartekus I did fork your repo and pulled down the babel-6-upgrade branch. Ran npm install then copied that folder to replace the node_modules/react-toolbox. 

Still I get the same error...

**Comment by hsrobmln** [comment] 2015-12-25 06:43
@natac13 Make sure you have a '.scss' entry in the module.resolve section of your webpack config.

**Comment by hsrobflavorus** [comment] 2015-12-25 06:44
@natac13 Make sure you have a '.scss' entry in the module.resolve section of your webpack config.

**Comment by natac13** [comment] 2015-12-25 13:11
Ok so I have followed the last instruction as well as removed the include property in the style loader.
![react-toolbox-webpack](https://cloud.githubusercontent.com/assets/10660283/12003036/a825f3f0-aade-11e5-9688-378a0e5c79ee.png)

I am able to get through the error I was having so thank you!!
-----------------------------------------------------------------------
## New Error
However now the button does not render like it should..
![react-toolbox-button](https://cloud.githubusercontent.com/assets/10660283/12003043/c7d86a16-aade-11e5-9d85-5ab60af18656.png)

The first two buttons are from material-ui which works... See the code for that page here.
![react-toolbox-home](https://cloud.githubusercontent.com/assets/10660283/12003048/ef7a4e0e-aade-11e5-91bb-32f663a33a2c.png)


At this point I feel pretty stupid since I am guessing I just don't understand how to get this setup. But I just cannot spend more time on this... 
Perhaps I will try again on my next project.

**Comment by javivelasco** [comment] 2015-12-25 20:05
@natac13 I guess you already checked the example repository and the configuration in the `docs` folder which is emulating an `npm` package. Did you??

This is kind of annoying because there are a lot of people having issues with the configuration. However, there is already a couple of configuration examples that should work for most people.

**Comment by javivelasco** [comment] 2015-12-25 20:06
Also, we can reopen if you feel like it's not a configuration issue. I just closed it to reduce noise between configuration issues and bugs/enhancements

**Comment by natac13** [comment] 2015-12-25 21:07
@javivelasco I really do apologize for the annoyance. I do recognize that this is also something completely on my end. Therefore I agree it should be left closed. I will look more closely at the `docs` folder to model my configuration off that. Thanks for the reply Merry Christmas.

**Comment by javivelasco** [comment] 2015-12-25 21:12
Don't forget to clone and check [here](https://github.com/react-toolbox/react-toolbox-example)! Thank you and merry christmas!! :dancer:

**Comment by natac13** [comment] 2015-12-26 02:39
So I have spent the last 4 hours trying to change my project to match the example... Was unsuccessful and now have lost the ability to run my project at all with webpack lol just been a very humbling day with regards to my knowledge.

**Comment by ajaysaini-sgvu** [comment] 2017-06-12 07:49
I installed it `npm install --save react-toolbox` and imported in my component

```
import AppBar from 'react-toolbox/lib/app_bar';
import Navigation from 'react-toolbox/lib/navigation';
import Link from 'react-toolbox/lib/Link';

```

I am not sure, why it is giving below error message. Does anyone know what could be the cause ? 

> Module not found: `D:\React JS\todo-app\node_modules\react-toolbox\lib\Link\index.js` does not match the corresponding path on disk `link`.
