### ISSUE TITLE
Default theme overrides custom theme

### ISSUE THREAD

**Issue by thesbros** [react-toolbox/react-toolbox#958] opened 2016-11-12 23:10 UTC
I have a ThemeProvider, which is given the following config:

```js
{
    RTList: require("../../styles/list.scss")
}
```

The contents of `list.scss` are:

```sass
$list-item-icon-font-size: 1.2rem;

@import "~react-toolbox/lib/list/theme";
```

This should change the icon font size of the list; however the default `list` theme is overriding my custom theme, as shown in this image:

![example](http://i.imgur.com/sr2EDsb.png)

What is the preferred way to fix this issue?

**Comment by borela** [comment] 2016-11-21 14:36
How are you importing the list component?

**Comment by thesbros** [comment] 2016-11-21 23:03
@borela 

In the React component?

```js
import {List} from "react-toolbox";
```

**Comment by borela** [comment] 2016-11-21 23:26
When you load it that way, it loads all default themes and it does indeed override any custom styles you did, I have a similar setup and to prevent that you have to load the raw components like so:

```Javascript
import List from 'react-toolbox/lib/list/List';
import Dropdown from 'react-toolbox/lib/dropdown/Dropdown';
// ...
```

That can get tedious quickly, so to simplify, I put these lines into a single file:

```Javascript
// components.js
export List from 'react-toolbox/lib/list/List';
export Dropdown from 'react-toolbox/lib/dropdown/Dropdown';
// ...
```

And then to import I can just do:
```Javascript
// some other file.js
import {List, Dropdown} from 'components.js';
```

**Comment by thesbros** [comment] 2016-11-21 23:42
That is.. inconvenient. I thought `react-css-themr` was supposed to merge the themes. Thanks either way!

**Comment by borela** [comment] 2016-11-21 23:53
It does but unfortunately the default themes have higher priority than the context ones, [I think it's considered a `configuration` theme or something like that](https://github.com/javivelasco/react-css-themr#combining-css-modules). I was going to modify this and send a pull request but the [next version is on the way](https://github.com/react-toolbox/react-toolbox/pull/666) and a lot of files were changed.

**Comment by javivelasco** [comment] 2016-11-25 18:42
Thanks for your comments @borela.

@thesbros I'm leaving you here some insights about this and the reasoning behind. First of all, take into account that importing like `import { List } from 'react-toolbox'` actually requires every JS and CSS inside the library so your final bundle will include *everything*. It's better to import from `lib` so you just require what you need.

That said, you can import, as @borela said, with `css` or *without* `css`. It is implemented like this because importing a component that requires the css for you forces to install and configure CSS Modules and we want to make it optional. The alternative is to pass custom modules to the components using `ThemeProvider` from `react-css-themr`. It is supposed to merge themes indeed, but merging just means concatenating classNames. More explicitly, this is what is happening for your case:

1. You add a module using context that import the same original CSS Module but with a sass variable overriden so it gets merged with the original.
2. You require a component with CSS so the original CSS is included.
3. The component is rendered with *both* original and custom classNames in each node. Each className has basically the same styles (as shown in your screenshot) but they are defined *twice* and, since they have the same priority, the one applied is the one that appears **the last** in the final CSS. As you can see, it is the original indeed because it is bundled *after* your custom.

The proper way to do this may vary depending on your intention:

1. If you want to override some properties, you can use a custom css module with just the classNames you want to override. Make sure the priority is higher by namespacing the custom component with a className and writing the same selector as used originally (this will be improved in the future).
2. If you want to change a variable for *every* component in react-toolbox add the variable to the webpack configuration so when the styles are transformed they get your variable and not the default.
3. If you want to use a custom component tweaking many properties, you can import a raw component and the original CSS overriding in the same file both variables and styles.

I know it's tricky to expose components in two ways but the alternative is to create two different distributions of react-toolbox which is more difficult to maintain. Ideally we import a component with styles but it's incompatible with the benefits of traditional CSS.

@borela I left a comment in #977 I think it's not possible!

Hope it helps ❤️

**Closed by javivelasco** 2016-11-25 18:42 UTC

**Comment by JulianJorgensen** [comment] 2017-05-17 20:02
Just chiming in that overriding theme styles is indeed a bit challenging. Still trying to find the heads and tales of whats going on. Obviously I don't want to use !important :)

**Comment by javivelasco** [comment] 2017-05-26 08:19
The issue is that as long as you use cascading and some complex selectors overriding is not easy because priority is on your side. You have to write same or more specific selectors which might be challenging in some cases. Also take into account that styles were written at first without thinking too much about customization, that's why sometimes there are too specific selectors. My approach would be to inspect how specific is the selector for the style you're overriding and to use the same or more priority.
