### ISSUE TITLE
Autocomplete vs NODE_ENV=development

### ISSUE THREAD

**Issue by deedoc** [react-toolbox/react-toolbox#993] opened 2016-11-24 12:13 UTC
Thx for great project!

When bundling my app with NODE_ENV=development, Autocomplete fails onChange behavior
It's because in Autocomplete:232 (search by text "select = (event, target)") event becomes Proxy and target becomes event. In that case "const newValue" resolving logic returns target.

Am I correct? Or this is my fault (incorrect usage of Autocomplete?)

**Comment by borela** [comment] 2016-11-24 15:39
I think it was due to event not being passed, but I cannot reproduce the issue, post a code to show the issue.

**Comment by deedoc** [comment] 2016-11-24 17:11
[rtb-993.zip](https://github.com/react-toolbox/react-toolbox/files/611882/rtb-993.zip)
Here is example.
First "npm install"
Then "npm run start-dev" to build with process.env.NODE_ENV=development (should see problem)
Then "npm run build-prod" to build with process.env.NODE_ENV=development (should see everything is ok)

Sorry for archive=)

**Comment by borela** [comment] 2016-11-24 17:32
This bug was fixed in #990 it only happens when you use selection with the mouse(try to type the option and press enter, it should work), you'll have to clone the dev branch and build it to use the patch.

After you build it, don't forget to delete the node_modules dir that will be created inside the react-toolbox's dir, still working on a way to [auto build](https://github.com/react-toolbox/react-toolbox/pull/992) projects targeting branches instead of npm versions.

**Comment by deedoc** [comment] 2016-11-25 07:12
Thx a lot! It worked for me.
Now i have following in my dependencies
`
"dependencies": {
    "react": "^15.4.0",
    "react-dom": "^15.4.0",

    "react-toolbox": "COMMENT: it's a dev branch (https://github.com/react-toolbox/react-toolbox/issues/993)",
    "react-toolbox": "git://github.com/borela/react-toolbox.git#autobuild",

    "immutability-helper": "COMMENT: unmet peer dependencies",
    "immutability-helper": "~2.0.0",
    "react-addons-css-transition-group": "^15.4.0",
    "classnames": "^2.2.0"
  }
`

**Comment by borela** [comment] 2016-11-25 17:25
You can change to `"react-toolbox": "git://github.com/react-toolbox/react-toolbox.git#dev"`, the only difference is that you will have to build it manually.

**Closed** 2016-11-25 20:23 UTC
