### ISSUE TITLE
Dropdown component cannot be populated with more than six values 

### ISSUE THREAD

**Issue by Adeyosola** [react-toolbox/react-toolbox#901] opened 2016-10-26 21:40 UTC
My app has about 40 options for users to select from, but react-toolbox dropdown only renders the first 6 options. Is the dropdown component pegged at 6 values or is there a way to work around that? Or is it a bug? I'm feeding the dropdown component with values from a JSON file.

**Comment by rubenmoya** [comment] 2016-10-28 14:55
I haven't been able to reproduce it, I created a dropdown with 18-20 items, and it shows the first 8 items, then scrolling inside the dropdown shows the rest of the items.

Have you checked with the react extension that the dropdown has 40 items in the prop `source`?

**Comment by Adeyosola** [comment] 2016-10-28 15:15
Hi, @rubenmoya I see it now, but i had to zoom in my browser to 25% to see more of the items not all. Is there a way to add a scrollbar to the dropdown component. I assumed that should be automatic. I am using the chrome browser on windows OS and without a scrollbar it is impossible to see all the items.  Any advice on how to get a scroll bar into the dropdown component?

**Comment by rubenmoya** [comment] 2016-10-28 15:18
You should be able to scroll inside the dropdown, that's the default behaviour, there's no scrollbar visible, but if you scroll inside the dropdown it should show you the rest of the items.

**Comment by Adeyosola** [comment] 2016-10-28 16:24
Thanks @rubenmoya. I don't know why I can't scroll inside the dropdown in chrome (not even with the arrow keys) but i was able to scroll inside the dropdown in mozilla- a scrollbar was actually visible.

**Comment by rubenmoya** [comment] 2016-10-31 20:39
That's weird, I'm using chrome too and I can scroll perfectly (the scroll bar is not visible tho)

**Comment by Adeyosola** [comment] 2016-11-02 18:06
Probably my version of chrome is the problem. However, I found out that I can scroll with the arrow keys if I click on the space at the left side of the dropdown. I'm still trying to figure out what is wrong though.

**Comment by javivelasco** [comment] 2016-11-19 21:59
@Adeyosola I'm closing since it looks like an isolated issue. If you feel like it's better to always show the scroll you can customize the style using CSS :)

**Closed by javivelasco** 2016-11-19 21:59 UTC
