### ISSUE TITLE
Mobile optimization

### ISSUE THREAD

**Issue by zwhitchcox** [react-toolbox/react-toolbox#122] opened 2015-11-17 18:12 UTC
Love this repository on desktop...any plans to make it responsive??

**Comment by javivelasco** [comment] 2015-11-17 18:16
Thanks @zwhitchcox ! 
Of course, we are going to work on it ASAP. We are going to review each component, one by one, on different screen sizes and add the queries to make it look properly on mobile.

**Comment by soyjavi** [comment] 2015-11-18 07:20
@zwhitchcox the idea is that each component fits correctly in any kind of screen. So, stay tunned...

best

**Comment by elliotatRetireup** [comment] 2015-11-19 18:25
Besides the size of the components, the ripple animation has a delay on click when using a touch interface. 

This shows when using phone hardware or simulating it using chrome dev tools

**Comment by javivelasco** [comment] 2015-11-19 18:29
Are you referring in general or in the site? Now for example `Button` is implemented to start the ripple `onMouseDown`. Maybe we can try to specifically start it with `onTouchStart` and see if the response is better... Apart from that we have to think how to boost performance. I know Polymer implements a different approach for the ripple effect.

**Comment by elliotatRetireup** [comment] 2015-11-19 18:32
In general. Even if the only thing displayed on the page is a single button the issue is still there. And it occurs even in chrome dev tools simulating a device. This leads me to believe it isn't performance related.

It might be because the click doesn't trigger on mobile until the finger is lifted, so onTouchStart might be a fix.

**Comment by javivelasco** [comment] 2015-11-19 19:05
Indeed. It's solved considering touch events for elements that use the ripple effect. Working on it and available in next release.

Thanks for the report @elliotatRetireup !

**Comment by javivelasco** [comment] 2015-12-20 17:35
Closed in favour of #224

**Closed by javivelasco** 2015-12-20 17:35 UTC
Labels: enhancement
