### ISSUE TITLE
Tabs arrows updating issue (1.3.x synced branch needed for PRs)

### ISSUE THREAD

**Issue by merraysy** [react-toolbox/react-toolbox#1767] opened 2017-11-28 19:05 UTC
Hey @javivelasco @soyjavi,

First of all, we are using `react-toolbox` extensively in our project and it's awesome thank you.

We are still using `v1.3.x` actually and not willing to upgrade in the near future, and we have some issues.

`Tabs` component do not update the arrows when their children count changes, they are updated only when the window resizes.

![Tabs Issue](https://d1ro8r1rbfn3jf.cloudfront.net/ms_159532/4McLv4bZdQMp0trpuab4xsqZUaPFyF/screencast%2B2017-11-28%2B18-40-57.gif?Expires=1511981015&Signature=DPw5f5unsavdRWki3hqwaM5tKK-rCn~--me-vRt9Ja1D-G1rgF-T2B75FE~luSg9IWPSlhNZu6R7SlBfEIbd8PIzcDQ-3pHem0hD3ENMBQ9YV6b8jWac7TqC3fuIwA80Kb5SbO-1a3vKgQLhgP9id6eFKpxtrOUcYg13brFIWIOfNx3LVC~awBlFl3quMf4chVpGmhvRRww1jBFa4opYvH6-SC-8ejn2oyGrrWskZA6Ycm9z6QYZmWOEQSvryOLY40izc~AJz05xQEBNNSZVhKY7GheS0jL27mlVy~FaVJFwF7JN7Vxc8dODRfaGYa8YjfeQvUCNa~xFJzpx7Gldqw__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

I've fixed the issue https://github.com/merraysy/react-toolbox/commit/5dff9cc4b8aa10bc9b77467588a95e5a871eee69 and would love to send a PR but there is no `branch` synced with `v1.3.x` anymore, may you please create one so we can work on other issues like the one already mentioned at #1678, #1246 and #314 that we still encounter.

**Comment by timurgarif** [comment] 2017-12-27 19:58
@merraysy, I believe [master](https://github.com/react-toolbox/react-toolbox/tree/master) is v1.3.4. The problem is a lot of PR's already pending... I think PR's to master could be accepted faster...

**Comment by merraysy** [comment] 2018-01-02 10:04
@timurgarif I've requested a pull fixing the same issue in the latest version https://github.com/react-toolbox/react-toolbox/pull/1768. Still, no response yet.

**Comment by rubenmoya** [comment] 2018-01-24 15:37
Closed in https://github.com/react-toolbox/react-toolbox/pull/1768

**Closed** 2018-01-24 15:37 UTC
