### ISSUE TITLE
Icons not aligned in Buttons (Safari 9.1.1)

### ISSUE THREAD

**Issue by finaiized** [react-toolbox/react-toolbox#557] opened 2016-06-10 18:34 UTC
![screen shot 2016-06-10 at 11 31 10 am](https://cloud.githubusercontent.com/assets/955189/15974752/f7ab388c-2efe-11e6-92b4-457ce878f935.png)

When viewing the demos in Safari 9.1.1, OS X 10.11.5, the icons in the buttons are off-center (it appears to only happen to the Material icons?). I've also reproduced this locally by using the latest version from npm (1.0.0) and creating a button with an icon. I've confirmed that it works properly on Chrome 52.

**Comment by Pyrolistical** [comment] 2016-06-16 06:35
dupe of https://github.com/react-toolbox/react-toolbox/issues/542

**Closed** 2016-06-16 16:08 UTC
