### ISSUE TITLE
Can't Theme it with react-css-themr

### ISSUE THREAD

**Issue by BernardoS** [react-toolbox/react-toolbox#1260] opened 2017-02-21 15:31 UTC
I'm using:
package.json: 
```json
"dependencies": {
    "react": "^15.4.1",
    "react-css-themr": "^1.7.2",
    "react-dom": "^15.4.1",
    "react-toolbox": "^1.3.4"
  }
```
webpack.config.js:
```javascript
{
        test: /\.(scss|css)$/,
        use: [
          'style-loader',
          {loader: 'css-loader', options: {module: true, sourceMap: true, importLoaders: 1, localIdentName: '[name]_[local]_[hash:base64:5]'}},
          {loader: 'sass-loader', options: {outputStyle: 'expanded', sourceMap: true}}
        ]
      }
```

index.js:
```javascript
import React from 'react'
import {render} from 'react-dom'
import {ThemeProvider} from 'react-css-themr'
import theme from './theme/theme.js'
import App from './app'
render(
  <ThemeProvider theme={theme}>
    <App/>
  </ThemeProvider>
, document.getElementById('root'))
```
theme.js:
```javascript
export default {
  RTRipple: require('./ripple.scss'),
  RTButton: require('./button.scss')
}
```
app.js:
```javascript
import React, {Component} from 'react'
import {Button} from 'react-toolbox/lib/button/Button'

export default class App extends Component {
  render () {
    return (
      <div>
        <Button raised primary>hi</Button>
      </div>
    )
  }
}
``` 
_theme.scss: 
```scss
@import "~react-toolbox/lib/colors";
$color-primary: $palette-red-500;
$color-primary-dark: $palette-red-700;
```
button.scss:
```scss
@import "theme.scss";
@import "~react-toolbox/lib/button/theme";
```

ripple.scss:
```scss
@import "theme.scss";
@import "~react-toolbox/lib/ripple/theme";
```

I basically followed the way of doing the theming that is in the [site](http://react-toolbox.com/#/install). to be more specific, the example in the section **Using SASS imports and context**

What is it that i'm doing wrong? I can't find a easy and intuitive way to style the components by the ThemeProvider and I know that this issue probably is uncessary. Still.... ><

**Comment by javivelasco** [comment] 2017-03-08 21:15
I think the problem is that you are passing `module` option instead of `modules` to `css-loader`. Then, it is including the styles but not resolving into a Javascript object with the classnames. I'm pretty sure that just adding an `s` to that option will make it work 😁

Otherwise, please reopen!

**Closed by javivelasco** 2017-03-08 21:15 UTC
