### ISSUE TITLE
Bug: Sidebar + Multiline Input = incorrect handleAutoResize height calculation

### ISSUE THREAD

**Issue by matt-d-rat** [react-toolbox/react-toolbox#1129] opened 2017-01-10 07:10 UTC
**React:** v15.4.0
**React Toolbox:** v1.3.4

**Description**
The `handleAutoResize` handler for a multiline Input is calculating a larger than expected height value when mounted in a Sidebar whose width is currently transitioning as a result of setting its `pinned` prop from `false` to `true`.

This is because the textarea value is wrapping, due to the width of the Sidebar parent at the time, resulting in the `handleAutoResize` height calculation being considerably larger than the actual height the element will be when the Sidebar transition is complete.

The following code demonstrates how to reproduce the bug:

```js
import React from 'react';
import { Layout, Sidebar, Button, Input } from 'react-toolbox';

export default class LayoutTest extends React.Component {
    state = {
        sidebarPinned: false,
        value: 'When the sidebar width is transitioned overtime, the child input\'s handleAutoSize function will incorrectly calculate the height due to this long text being wrapped.'
    };

    handleChange = (value) => {
        this.setState({ value });
    };


    toggleSidebar = () => {
        this.setState({ sidebarPinned: !this.state.sidebarPinned });
    };

    render() {
        const buttonLabel = this.state.sidebarPinned ? 'Hide sidebar' : 'Show sidebar';

        return (
            <Layout>
                <Button label={buttonLabel} onClick={this.toggleSidebar} />
                <Sidebar pinned={ this.state.sidebarPinned } width={ 50 }>
                    <div>
                        <Input
                            type="text"
                            value={this.state.value}
                            onChange={this.handleChange}
                            multiline />
                    </div>
                </Sidebar>
            </Layout>
        );
    }
}
```

Overriding the Sidebar CSS `transition-duration` property to be `0s` results in the calculation of `handleAutoResize` being correct.

Delaying the call to `handleAutoResize` in the Input `componentDidMount` by >=350ms (0.35s being the amount `transition-duration` is set to for the Sidebar) also results in the calculation being correct.

Both of these solutions feel a bit hacky to me though. Perhaps the Sidebar should be transitioned by a different property instead of `width`?

**Comment by javivelasco** [comment] 2017-01-20 18:29
Thank you for such a detailed issue! I've tried to reproduce the issue in the latest beta but the components for layout have been rewritten. I think the issue can be solved by debouncing the `handleAutoResize` but since I couldn't reproduce it it wasn't possible.

Maybe it's just working in the latest so I'm closing. Please, try to reproduce it in the latest version and if it still happens feel free to reopen so I can try to debug it again!

**Closed by javivelasco** 2017-01-20 18:29 UTC
