### ISSUE TITLE
Unable to resolve ../helpers.css

### ISSUE THREAD

**Issue by dhaundy** [react-toolbox/react-toolbox#1069] opened 2016-12-19 18:33 UTC
If a scss file imports app_bar/theme.css (or other similar file), webpack build generates the error that ../helpers.css could not be resolved. I tried using resolve-url-loader but it didn't help.

PS: It would be great if a working example is maintained with every release. If it's already there, could you please point it out?

**Comment by javivelasco** [comment] 2016-12-19 19:49
I'm going to create a new example with this version as part of the migration to CSS Next. It's going to be published with a guide and a roadmap. About the issue, there is a lot of issues resolving paths for css modules. There should be a `from` option for the postcss transform. If you specify it as the root of react-toolbox components it should work fine. Check out [here](https://github.com/react-toolbox/react-toolbox-themr/blob/master/src/postcss.js) for an example config of what you need to transform

**Comment by landabaso** [comment] 2016-12-20 14:17
I also hit the same problem. Webpack complains about not finding `../helpers.css` when it's used for composition.

For example, in:
```
node_modules/react-toolbox/lib/button/theme.css
```
there is a:
```
composes: reset from '../helpers.css';
```

And `helpers.css` can be found at `node_modules/react-toolbox/lib/`.
I'm surprised Webpack does not load from a relative path just fine. Strange.

Isn't it there we can simply put in wepack.config.js so that postcss+composes relative paths work without using the JS API?

**Comment by landabaso** [comment] 2016-12-21 08:11
@dhaundy, while we dig and find the problem I suggest you copy (or better link) the `helpers.css` file from `node_modules/react-toolbox/lib` to the `".."` of the path from where you are importing the parent file that composes with reset (`app_bar/theme.css` in you example).

That tricks webpack and lets you compile just fine. Note this is only a trick.

I believe the real issue is not related to react-toolbox but a bug in the loaders. The `@import` directives resolve just fine. But `composes` fail to resolve for whatever reason...

**Comment by javivelasco** [comment] 2016-12-23 18:21
@landabaso setting the webpack context might make it work

**Comment by landabaso** [comment] 2016-12-28 09:00
@javivelasco could you please elaborate a bit more how to do it?
I read the context webpack docs but still could not get an idea how to solve the problem.

**Comment by lucasljj** [comment] 2016-12-29 15:33
I noticed that replacing the relative path with an absolute makes the thing work

example in file lib/button/theme.css:

**replace:** composes: reset from '../helpers.css';
**with this:** composes: reset from '/home/lucas/react-toolbox-example-webpack2/node_modules/react-toolbox/lib/helpers.css';

**Comment by landabaso** [comment] 2016-12-29 16:50
@lucasljj that's a workaround. Similar to linking the helper file to the ".." of the path from where you are importing the parent file that composes with reset.

 I believe it's a problem in the loaders / webpack. The `@import`s resolve OK but the path in the `composes` are not correctly resolved.

**Comment by lucasljj** [comment] 2016-12-29 16:58
Yep, it's a problem in the loaders :/

**Comment by razor-x** [comment] 2016-12-31 20:25
Running into this issue going from beta.2 to beta.4 using Brunch with 

```
    "postcss-brunch": "^2.0.5",
    "postcss-cssnext": "^2.8.0",
    "postcss-import": "^7.1.3",
```

**Comment by javivelasco** [comment] 2017-01-05 01:51
I had the issue with react-toolbox-themr and it's a problem with the css loader resolving paths for modules. There is a workaround with webpack context but I made it work like [this](https://github.com/react-toolbox/react-toolbox-themr/blob/master/src/postcss.js#L57). All you need to do is to specify the root path from where you are transforming. The root should be `components` of course. Since it's a configuration issue, I think this can be closed to reduce noise but you are free to keep writing here. I'll help as much as I can!

**Closed by javivelasco** 2017-01-05 01:51 UTC
Labels: enhancement

**Comment by waldnercharles** [comment] 2017-01-10 14:07
I know this is closed, but I just filed a similar issue because of this. Having something in your readme would help new adopters.

You might also consider working around the bug on your end rather than relying on developers to look through closed issues.

All that said; do you have a webpack example? I'm not sure how to consume the `from` property from webpack.

**Comment by javivelasco** [comment] 2017-01-11 08:46
@waldnercharles you can skip the setup using [react-toolbox-themr](github.com/react-toolbox/react-toolbox-themr). Actually the plan is to remove that module too but meanwhile it can be solved with configuration. Unfortunately the example respository is outdated so you can always check the webpack configuration in internal `spec` page of in the `docs` project

**Comment by waldnercharles** [comment] 2017-01-12 00:24
I've followed these steps:
```
git clone https://github.com/react-toolbox/react-toolbox/
cd react-toolbox/docs
npm install
webpack --config webpack.config.development.js
```
Results in:
```
 ERROR in ./~/css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./app/components/layout/main/style.css
    Module not found: Error: Cannot resolve 'file' or 'directory' ../helpers.css in C:\react-toolbox-dev\docs\app\components\layout\main
     @ ./~/css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./app/components/layout/main/style.css 3:10-218 10:38-246 15:60-268 16:56-264 17:64-272 19:60-268
```

Perhaps I misunderstood? Please let me know if I've messed up any steps, or if you are unable to reproduce.

**Comment by javivelasco** [comment] 2017-01-12 20:06
The project has an own `package.json` with a start script. Just type `npm start` after installing inside the `docs` folder. It should work. It's an issue related with the path resolution which might be different if you're running the project like that :S

**Comment by waldnercharles** [comment] 2017-01-12 23:59
I've done as you said with `npm start` from within the docs folder. I'm still unable to get it to work. `composes` looks like it's having trouble resolving a relative path. It attempts to resolve the `composes` from the location that the file was originally imported from.

So it is looking for `../helpers.css` from `docs/app/components/layout/main/style.css`.

Does `npm start` work for you? if so, what exact version of `css-loader`, `postcss-loader`, and `postcss-import` do you have installed?
