### ISSUE TITLE
Cannot theme properly components without !important

### ISSUE THREAD

**Issue by AlesMenzel** [react-toolbox/react-toolbox#1546] opened 2017-06-21 10:25 UTC
Bundler: Webpack 3.0
React-Toolbox: 2.0.0-beta.12

Hello, iam having an issue after upgrading (from 1.x) to React-Toolbox 2.0@beta. For some reason the styles are applied in the order of `mythemes `and then `react-toolbox themes` which causes overriding (see image below).

<img width="388" alt="jpjbedckqrkqr8syq3qkjq" src="https://user-images.githubusercontent.com/8976542/27379638-5ad1e956-567c-11e7-9b37-f2f53356d480.png">

Configuration: Webpack loader snippet:
```
{
	test: /\.(scss|sass|css)$/,
	exclude: [path.resolve(__dirname, "src/app/styles")], // Exclude global styles
	use: extractSass.extract({
		fallback: 'style-loader',
		use: [
			{
				loader: 'css-loader',
				options: {
					// sourceMap: true, // TODO Breaks image paths
					modules: true,
					importLoaders: 1,
					// naming of module classes
					localIdentName: (() => {
						if (isProduction) {
							return '[hash:base64:5]';
						}

						return '[path][name]__[local]';
					})(),
					minimize: isProduction
				}
			},
			{
				loader: 'postcss-loader',
				options: {
					ident: 'postcss',
					plugins: () => [
						cssNext({
							features: {
								customProperties: {
									variables: reactToolboxVariables,
								},
							},
						}),
						modulesValues
					],
					sourceMap: true
				}
			},
			{
				loader: 'sass-loader',
				options: {
					sourceMap: true
				}
			}
		]
	})
},
```

**Comment by tobiasandersen** [comment] 2017-06-21 11:14
Please see my answer [here](https://github.com/react-toolbox/react-toolbox/issues/1488) and try if that works.

**Comment by AlesMenzel** [comment] 2017-06-21 11:22
Yes, you are absolutely correct about the specificity issue - both of the styles (as shown in the picture) have the same specificity: `.label.active` but the custom styles are loaded `before` (this is very important) the react-toolbox default `label.active` style. So my question is: Why does the webpack loads the styles in that order even if my component looks like this:

```
import React from 'react'

/* Components */
import { Tabs, Tab } from 'react-toolbox/lib/tabs'

/* Styles */
import tabsTheme from './theme/tabs.scss'

/**
 * Tabs for navigation
 */
const MyTabs = ({index, onChange}) => {
	return (
		<Tabs index={index} onChange={onChange} theme={tabsTheme}>
			<Tab label='Tab1'/>
                         ... more tabs
		</Tabs>
	);
};

export default MyTabs
```

**Comment by mikeyGlitz** [comment] 2017-06-25 04:16
Having the same problem. Tried to create a component using the following CSS
```css
.appBar {
background-color: #c00;
}
```
```js
import { AppBar } from 'react-toolbox/lib/app_bar'
import theme from './error-app-bar.css'

export default props => <AppBar {...props} theme={theme} />
```

And I still get the standard blue `AppBar`. Adding `!important` to the style sheet makes the custom style apply:
```css
.appBar {
background-color: #c00 !important;
}
```

**Comment by flushentitypacket** [comment] 2017-06-28 21:25
@tobiasandersen I don't see how you can increase specificity since classnames get randomized in most implementations of CSS modules. Can you provide an example? That would be super helpful!

**Comment by tobiasandersen** [comment] 2017-06-28 21:30
@flushentitypacket e.g. both `div.item` and `.container .item` has greater specificity than `.item`.

**Comment by flushentitypacket** [comment] 2017-07-03 14:27
@tobiasandersen Ah, I just realized that I was confusing something about CSS classes--`.foo.bar` is not more specific than `.baz`, since they are both actually a single class. So yeah, your solution should work.

This is still an issue that should certainly be resolved!

**Comment by creeperyang** [comment] 2017-08-18 03:14
Exactly the same problem.

And I don't think give a higher specificity rule is a good solution. It will make custom style more complex ( we should dive into the applied rules).

And I think the react-toolbox itself handles style rule incorrectly:

![image](https://user-images.githubusercontent.com/8046480/29442793-73e2da92-8406-11e7-96a6-23d99213d0cc.png)

**Comment by jmar777** [comment] 2018-02-21 19:36
Selector specificity questions aside, I am kind of confused regarding the order that styles are being added to the generated stylesheet. I just upgraded from 1.3 to the latest 2.x beta, and now my style overrides are failing to "win" as well.

Specifically, this happens in case where there was a specificity "tie", and the regression in styling behavior happens where react-toolbox styles are now being included _after_ mine, whereas before they were included _before_. I suppose this seems like a webpack configuration issue, but I'm at a loss on what of significance would have changed regarding inclusion order...

**Comment by jmar777** [comment] 2018-02-21 20:14
Update: sorry about the noise, turns out this was indeed a webpack configuration issue. I'll post the explanation/solution here just in case anyone else is running into the same problem:

1. Back on react-toolbox 1.3, I had a webpack rule for `.scss` files, which was setup to work for both our project-specific styles, as well as for react-toolbox.
2. After upgrading to react-toolbox 2.x, as a result of no longer utilizing Sass, I created a new rule for `.css` files that conformed to the new react-toolbox expectations.

It turns out that it was the presence of _distinct rules for_ `.scss` files and `.css` files that was causing the generated stylesheet to not reflect their respective import orders. The solution was to create a single, unified rule that handles them both.

Here's my updated, single webpack rule for `.css` and `.scss` files, which may be useful to others who are making the upgrade to 2.x, and don't want to throw out their existing Sass resources. As written here, it satisfies everything we carried over from the old version, as well as the new styles exported by react-toolbox:

```js
{
  test: /\.s?css$/,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      {
        loader: 'css-loader',
        options: {
          modules: true,
          sourceMap: true,
          importLoaders: 1,
          localIdentName: "[name]--[local]--[hash:base64:8]"
        }
      },
      {
        loader: 'postcss-loader',
        options: {
          ident: 'postcss',
          plugins: loader => [
            require('postcss-import')({
              root: path.resolve(__dirname, '../')
            }),
            require('postcss-mixins')(),
            require('postcss-each')(),
            require('postcss-cssnext')({
              features: {
                customProperties: {
                  variables: {
                   // note: these are obviously project specific for us,
                   // but I'm leaving them in for demonstrative
                   // purposes. ;)
                    'color-background': 'rgb(250, 250, 250)',
                    'color-primary': '#32c274',
                    'color-primary-dark': '#fff'
                  }
                }
              }
            })
          ]
        }
      },
      {
        loader: 'sass-loader',
        options: {
          includePaths: [
            path.resolve(__dirname, '../public/src')
          ],
          data: [
            '@import "sass/variables.scss";',
            '@import "sass/mixins.scss";',
            '@import "~normalize.css";',
            '@import "sass/global.scss";',
          ].join('')
        }
      }
    ]
  })
}
```

**Comment by rubenmoya** [comment] 2018-02-25 16:53
Thank you for your answer @jmar777! Closing since seems to be solved using your configuration :)

**Closed by rubenmoya** 2018-02-25 16:53 UTC
Labels: Type: Question
