### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by abelaska** [react-toolbox/react-toolbox#61] opened 2015-11-06 07:22 UTC
Have anybody tried to use react-toolbox for server-side rendering?
Is it even possible the way it is implemented now because of the close integration with react-transform-hmr?

**Comment by javivelasco** [comment] 2015-11-06 09:49
I did not try server side rendering yet! But I think it's possible of course. Maybe someone can try it and give feedback about it? The integration with HMR shoudn't be a problem cause it's only for development purposes.

**Comment by abelaska** [comment] 2015-11-06 18:17
I tried to integrate react-toolbox into https://github.com/este/este and got this error. The problem is ho the react-transform-hmr is used in react-toolbox.

/home/abelaska/Projects/ten-app/node_modules/react-transform-hmr/lib/index.js:51
    throw new Error('locals[0] does not appear to be a `module` object with Hot Module ' + 'replacement API enabled. You should disable react-transform-hmr in ' + 'production by using `env` section in Babel configuration. See the ' + 'example in README: https://github.com/gaearon/react-transform-hmr');
    ^

Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr
    at proxyReactComponents (/home/abelaska/Projects/ten-app/node_modules/react-transform-hmr/lib/index.js:51:11)
    at Object.<anonymous> (/home/abelaska/Projects/ten-app/node_modules/react-toolbox/lib/input/index.js:47:65)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/abelaska/Projects/ten-app/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/abelaska/Projects/ten-app/node_modules/react-toolbox/lib/autocomplete/index.js:39:14)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/abelaska/Projects/ten-app/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

**Comment by javivelasco** [comment] 2015-11-07 09:31
We are going to try to create an example integrating Toolbox with [este/este](https://github.com/este/este). Right now we need to prioritize and help here is very welcome. @ustccjw helped a lot with HMR and workflow, maybe he can take a look on it?

**Comment by ustccjw** [comment] 2015-11-07 09:48
sorry, i do not know the context. But if you want to disable hmr, you can set NODE_ENV excepet development

**Comment by EnzoMartin** [comment] 2015-11-08 20:20
The problem is that when you specify `react-toolbox` as a dependency, it runs `npm run babel && npm run sass` which if you're using it locally, uses all the Babel development configs which includes the hotloader, transforms, etc.

If your project you're building doesn't make use of those things, or if you try to use them server side without the help of Babel, then the compiled `react-toolbox` will throw a variety of errors as it's expecting the global scope to be populated with certain things like the module hot loader, which of course are not present.

The solution is to change that compile step to be compiling for production as the package is published and therefore cannot be considered to be in local development (unless you're editing the `react-toolbox` project itself of course).

Expecting the `NODE_ENV` variable to be set to not `development` isn't realistic as local development efforts are not going to use anything other than `development` while they build their application

**Comment by javivelasco** [comment] 2015-11-08 20:31
There is another issue where I realized that I was generating the build without `production` flag. Being that the case the javascript was compiled with all those development dependencies as you said. I've fixed the build yesterday, can you try with the latest package and check if it's resolved??

Thanks! :smile:

**Comment by EnzoMartin** [comment] 2015-11-08 20:39
Seems to be working now :+1:

**Comment by javivelasco** [comment] 2015-11-08 20:48
Great! Can we close this issue?

**Comment by EnzoMartin** [comment] 2015-11-08 21:08
Should be yes, go for it.

**Comment by javivelasco** [comment] 2015-11-08 21:17
Nice! Thanks :)

**Closed by javivelasco** 2015-11-08 21:17 UTC

**Comment by KinghtOfHell** [comment] 2016-04-15 20:44
Is there example of server rendering  with react toolbox?

**Comment by javivelasco** [comment] 2016-04-15 21:00
Not yet but it should be pretty easy following other boilerplate projects. You just need to set up your backend with CSS Modules to be able to require `scss`. Here is a small snippet to do it:

```js
var hook = require('css-modules-require-hook')
var sass = require('node-sass')
var path = require('path')

hook({
  rootDir: path.join(__dirname, '../'),
  extensions: [ '.scss' ],
  generateScopedName: process.env.NODE_ENV === 'development'
    ? '[name]__[local]___[hash:base64:5]'
    : '[hash:base64:5]',
  preprocessCss: function (data, filename) {
    return sass.renderSync({
      data: data,
      file: filename,
      includePaths: [
        path.join(__dirname, './app/components'),
        path.join(__dirname, './node_modules')
      ]
     }).css
  }
})
```
