### ISSUE TITLE
Discourage Binding Syntax for Input onChange Function Prop

### ISSUE THREAD

**Issue by adrianmc** [react-toolbox/react-toolbox#652] opened 2016-07-18 09:08 UTC
I've been looking at the docs for the Input element and I think the suggested way of data binding is a little bit unwieldy. More specifically, I'm talking about how to handle the data you get from the Input components. I propose that we change the docs to reflect a better approach.

For context, I was inspired by [this gist](https://gist.github.com/ffxsam/21c1886e0e174e762d73aeb3541e7e26) which I got from [this Reddit post](https://www.reddit.com/r/webdev/comments/4tbha0/data_binding_code_in_9_javascript_frameworks/d5gas4o).
# What we have now

Currently, the suggested way of using the Input component is to bind the data name with the function call:

``` jsx
onChange={this.handleChange.bind(this, 'email')}
```

We already know that the AirBnB style guide discourages using `.bind()` inside the render function ([source](https://github.com/airbnb/javascript/tree/master/react)). As explained [here](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md):

> A bind call or arrow function in a JSX prop will create a brand new function on every single render. This is bad for performance, as it will result in the garbage collector being invoked way more than is necessary.

It also looks really bad in my opinion. This is what we have with the current approach:

``` jsx
class Component extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      email: '',
      password: '',
    };
  }

  handleChange(name, value) {
    this.setState({
      [name]: value,
    });
  }

  render() {
    return (
      <div>
        <Input
          type="email"
          label="Email Address"
          value={this.state.email}
          onChange={this.handleChange.bind(this, 'email')}
          required
        />
        <Input
          type="password"
          label="Password"
          value={this.state.password}
          onChange={this.handleChange.bind(this, 'password')}
          required
        />
      </div>
    );
  }
}
```
# What I propose

Instead, what we can do is add an `id` attribute to each input and bind `this` in the constructor. This allows us to simply write:

```
onChange={this.handleChange}
```

... which I think is a lot better and more closely resembles how functions are usually passed in as props. Revising the above example with this way of data binding:

``` jsx
class Component extends React.Component {
  constructor(props) {
    super(props);
    this.handleChange = this.handleChange.bind(this);
    this.state = {
      email: '',
      password: '',
    };
  }

  handleChange(value, event) {
    this.setState({
      [event.target.id]: value,
    });
  }

  render() {
    return (
      <div>
        <Input
          id="email"
          type="email"
          label="Email Address"
          value={this.state.email}
          onChange={this.handleChange}
          required
        />
        <Input
          id="password"
          type="password"
          label="Password"
          value={this.state.password}
          onChange={this.handleChange}
          required
        />
      </div>
    );
  }
}
```
# Ideally

In the [example gist](https://gist.github.com/ffxsam/21c1886e0e174e762d73aeb3541e7e26) from Reddit, the `handleChange()` function is more straight-forward than in my example.

My way:

``` jsx
handleChange(value, event) {
  this.setState({
    [event.target.id]: value,
  });
}
```

His way:

``` jsx
handleChange({ target }) {
  this.setState({
    [target.id]: target.value,
  });
}
```

This is because `onChange` for a traditional `<input>` element is usually called with just the event. In contrast, the Input component from the current implementation in React-Toolbox calls it with the value first and then the event:

``` jsx
if (this.props.onChange) this.props.onChange(event.target.value, event);
```

Source: [Line 77 of Input.js](https://github.com/react-toolbox/react-toolbox/blob/dev/components/input/Input.js#L77)

This is why the example I gave is different from the one in the Gist. In the future, we may want to change this to better reflect the natural behaviour of an input element:

``` jsx
if (this.props.onChange) this.props.onChange(event);
```

But this will be a breaking change since I already have written my code to suit this approach. It's okay to keep going with what we have, but it should probably be better documented as well.

**Comment by javivelasco** [comment] 2016-08-06 19:25
Yeah, I didn't noticed about the binding problem. I've looked into the components and there are some places were `bind` is done internally. I think the approach of id would work in most cases. I'm going to update those places where the rendering function uses bind and then we can change the docs too.

About the breaking change... I think we better keep it that way for now but maybe documenting better. Although it's not very idiomatic to pass the value as the first parameter, I think it's quite handy though. Maybe the best would be to move it to a second parameter.

**Comment by adrianmc** [comment] 2016-08-06 21:24
@javivelasco great response, I agree with you on pretty much everything. As an actionable itemized summary of what you just said:

- [ ] Refactor `.bind()` calls in `render()` for the components, internally
- [ ] Refactor `.bind()` calls in `render()` for the docs
- [ ] Improve inputs documentation to show that `.onChange()` is called with `onChange(value, event)`

[These search results show all instances in the code for where `.bind` exists.](https://github.com/react-toolbox/react-toolbox/search?utf8=%E2%9C%93&q=.bind)

**Comment by javivelasco** [comment] 2016-08-07 17:54
There are places where I'm not sure what to do. For example, [here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/autocomplete/Autocomplete.js#L250) we are creating a new function with each render but in my opinion relying on the `id` prop passed down could be error prone since we assume the rendered id is bound to the same node as the event handler which could not be true.

I can't find any helper in [recompose](https://github.com/acdlite/recompose) either. Sometimes what you want to bound is a complex object. What should we do with that? Suggestions?

**Comment by adrianmc** [comment] 2016-08-07 19:55
@javivelasco regarding the example you linked to, I would say that the problem lies in the Chip component. More specifically, [here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/chip/Chip.js#L25):

```jsx
<span className={theme.delete} onClick={onDeleteClick}>
```

Instead, it should probably be something like:

```jsx
<span className={theme.delete} onClick={this.handleDeleteClick}>
```

And in an internal method:

```jsx
handleDeleteClick(event) {
  const targetKey = this.props.key;
  this.props.onDeleteClick(event, targetKey);
}
```

That way, your [line 250](https://github.com/react-toolbox/react-toolbox/blob/dev/components/autocomplete/Autocomplete.js#L250) in the Autocomplete component no longer require the `.bind()`:

``` jsx
onDeleteClick={this.unselect}
```

And your [`unselect()` function](https://github.com/react-toolbox/react-toolbox/blob/dev/components/autocomplete/Autocomplete.js#L234-L240) is now:

```jsx
unselect (event, key) {
  if (!this.props.disabled) {
    const values = this.values(this.props.value);
    values.delete(key);
    this.handleChange([...values.keys()], event);
  }
}
```

Note that I switched the position of the parameters from `(key, event)` to `(event, key)` based on our previous discussion, although I'm okay with staying with the current convention as well. Of course, the documentation should be updated to show how to use this.

Regarding Recompose, I haven't personally used it, but it looks intriguing so thanks for the share. I'll try to learn how to use it over the week.

**Comment by adrianmc** [comment] 2016-08-07 20:05
I can see why you may not want Chip to be aware of a key though. It's really kind of a trade-off. It's rare that chips are used in isolation, but if you want to avoid specifying key for Chip, there is another work-around that might be viable.

Instead of:

```jsx
handleDeleteClick(event) {
  const targetKey = this.props.key;
  this.props.onDeleteClick(event, targetKey);
}
```

You can pass in a reference to all of its props:

```jsx
handleDeleteClick(event) {
  this.props.onDeleteClick(event, this.props);
}
```

**Comment by adrianmc** [comment] 2016-08-07 20:13
I did a bit of searching, and some of the suggestions here make a lot of sense:

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

According to the ProTips section, we could pull in the Chip into its own ChipItem component and apply a function there instead.

This is probably a way better solution than what I was proposing above. I'm a little sleep-deprived.

**Comment by javivelasco** [comment] 2016-08-07 20:42
The suggestions from eslint make a lot of sense. Gonna work on that tomorrow

**Comment by adrianmc** [comment] 2016-08-08 03:12
@javivelasco let me know where I can help. I'd love to submit a PR, but don't want to overlap on work you are currently doing

**Comment by javivelasco** [comment] 2016-08-08 08:09
Thanks @adrianmc ! It shouldn't be to difficult so no worries :) I'd rather would like to get help on other bug fixes!

**Comment by jagged3dge** [comment] 2016-08-14 16:43
Since the Toolbox is already using Babel with `stage-0` preset, maybe leveraging [ES7 property initializers](https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#autobinding) would be the best way to future-proof?

**Comment by javivelasco** [comment] 2016-08-21 17:14
Yeah, we do. The issue is more with rendering functions that binds a value and not the context. For example: `items.map(item => <li onClick={this.handleClick.bind(this, item.value)}>{item.name}</li>`)

**Comment by gregegan** [comment] 2016-08-30 23:25
The `<Input />` documentation says it receives two props `(name, value)`. The implementation seems to provide the value and a SyntheticEvent. `(value, event)`. 
https://github.com/react-toolbox/react-toolbox/blob/dev/components/input/Input.js#L92

I assume the documentation is incorrect here?

**Comment by gregegan** [comment] 2016-08-31 16:59
👍 to removing the bind syntax in the render method and improving the docs for callback. I think just passing the SyntheticEvent to the callback would be great.

**Comment by javivelasco** [comment] 2016-09-03 11:58
I wanted to drop some thoughts here. BTW this is coming after PostCSS migration. 

I'm recently trying out redux-form and I saw that they consider that `onChange` event can come with either an event of a value. In react-toolbox case, passing the value first allows you to debounce the callback with no pain. As many of you know, debouncing consuming the `event` is not a good practice because the `event` is pooled out after the triggering. If you want to debounce a callback were the event is consumed it needs to be persisted.

This is kind of shitty and for those situations it's better to just pass the value. I was thinking that if the value is passed as something complementary to the event, binding the value should be done manually. I think the opposite is better. If you want to consume from the event it's better to look for it.

Also, for example, consider when you navigate a list with keyboard and select an element by using the spacebar or something. If the component has an `onChange` callback, isn't it better to pass the value? I mean, the event would be different if the change come from keyboard event of click event but still, you are changing just a value. Then if you want to inspect the event you can get it from a second argument. (Note that ideally you'd have `onSelect` callback so it won't matter click of keyboard).

So, I think it's maybe a better API to provide first the value and then the event, not otherwise.
What do you think?

**Comment by Tzelon** [comment] 2016-10-13 14:37
Hey,
Any update on this issue ? I'm searching for the write approach on this. 
Should I use the bind approach for now ?

**Comment by javivelasco** [comment] 2016-11-04 10:52
Closing in favor of this other issue

**Closed by javivelasco** 2016-11-04 10:52 UTC
Labels: enhancement, feedback wanted, help wanted

**Comment by mulyoved** [comment] 2017-03-11 08:58
Also #932 is close documentation still use .bind(), guess better to reopen this task for now or create new one

**Comment by snirlugassy** [comment] 2017-04-23 20:12
https://medium.com/codealong/generic-input-handler-with-react-js-44a97e22cd0d
i wrote something about it!
