### ISSUE TITLE
Hint text for inputs?

### ISSUE THREAD

**Issue by tnrich** [react-toolbox/react-toolbox#292] opened 2016-02-03 21:50 UTC
Hey there,

I didn't see the option to supply a hint text to react-toolbox Input elements: http://react-toolbox.com/#/components/input

Does this option exist, and if not, is there a workaround to get hint texts?

Thanks!

**Comment by KerenChandran** [comment] 2016-02-04 14:43
You can use the placeholder or label property.

<Input type='text' label='Name' name='name' value={this.state.name} onChange={this.handleChange.bind(this, 'name')}  />

label will be initially placed on the field and then go to the top when the field is selected.
placeholder will act like it does on a normal input field, ie. it will only be visible if the field doesn't contain text.

The problem is you can't use both as they initially overlap, but when the field is active, the label is pushed to the top and behaves like it should.

**Comment by tnrich** [comment] 2016-02-04 17:27
Hmm thanks for the response. That seems like a bug to me. Shouldn't you be
able to use both a label and a hint text?

**Comment by KerenChandran** [comment] 2016-02-04 17:34
Ya I was surprised by this too. Material-ui has that feature built in on their demo page, so I believe this is a bug. See 'Floating Label' field: http://www.material-ui.com/#/components/text-field

**Comment by javivelasco** [comment] 2016-02-04 19:38
As far as I know, the Material Spec does not have a placeholder consideration. I guess we can tweak this a bit to display a placeholder when the component is focused. As @KerenChandran said, you can do it now but it overlaps with the label.

**Comment by tnrich** [comment] 2016-02-04 21:32
I think that would be a nice improvement @javivelasco  +1 :)

**Comment by arlair** [comment] 2016-02-23 16:43
I just found this as well and was going to report it.

Cool project and finding the code easy to read. Nice job :).

**Comment by javivelasco** [comment] 2016-02-25 07:45
Thanks @arlair :) Gonna label it as enhancement.
As I always say, help here is appreciated!

**Closed** 2016-03-20 23:52 UTC
Labels: enhancement
