### ISSUE TITLE
Ripple animation causes whole page to repaint

### ISSUE THREAD

**Issue by elliotatRetireup** [react-toolbox/react-toolbox#142] opened 2015-11-19 22:32 UTC
Found this issue while testing on my Lg G2 with Chrome.

Ran a list with 1 button vs a list with 100 buttons.

Clicking a button on the 1 button list renders the ripple fluidly.

Clicking a button on the 100 button list renders the ripple with a low framerate.

@EnzoMartin discovered that this was because the whole page was being repainted with every frame of the ripple animation.

**Comment by javivelasco** [comment] 2015-11-20 13:26
The problem is that in the initial implementation we animated `width` and `height` though a transition. This makes the browser to repaint. Furthermore, the ripple was positioned with `absolute` and, although this is not animated, it's also provoking a repaint.

The solution I've implemented gets rid of absolute positioning and animating width/height variations. Instead now it's animation a `transform: scale()` from 0 to 1. The position is changed using `transform: translate3d`. This allows to have a huge performance boost.

It will be released during the afternoon.

**Closed** 2015-11-21 11:59 UTC
Labels: bug, next release
