### ISSUE TITLE
Inline Datepicker

### ISSUE THREAD

**Issue by tarrencev** [react-toolbox/react-toolbox#834] opened 2016-10-02 21:13 UTC
I'd like to render the `DatePicker` component inline but it seems it is only possible to render it in a dialog as it exists today. Is that correct?

If so, would you guys be open to a PR that exposes a `Calendar` component that is not rendered in a dialog?

**Comment by q3452** [comment] 2016-10-03 08:51
This is a duplicate of #268 and others which request custom controls in table cells.  FYI, a current workaround is to insert the React component into your data as per #825.

`const users = [
  {name: 'Javi Jimenez', twitter: <Button label="@soyjavi" raised accent />, birthdate: new Date(1980, 3, 11), cats: 1},
  {name: 'Javi Velasco', twitter: <Button label="@javivelasco" raised accent />, birthdate: new Date(1987, 1, 1), dogs: 1, active: true}
];`

**Comment by tarrencev** [comment] 2016-10-03 17:03
@q3452 I'm not sure I follow, I don't see how these are related? The `DatePicker` as it stands today is wrapped in a `Dialog` by default. I think it would make sense and enable a lot of flexability if the [`Calendar`](https://github.com/react-toolbox/react-toolbox/blob/dev/components/date_picker/Calendar.js) component was exported as a first-party component similar to other React toolbox components. So that it can be used it inline like

```js
<Sidebar>
    <Calendar ... />
</Sidebar>
```

It's possible to import it directly from `react-toolbox/lib/date_picker/Calendar` but it requires manually  injecting the theme props and such.

Do you think it makes sense to export the `Calendar` as a first-party component? I'd be happy to put together a PR

**Closed** 2016-10-05 19:38 UTC

**Comment by javivelasco** [comment] 2016-10-08 10:43
Is it exposed already? If not we can do it without any side effects if you find it useful

**Comment by thisischrisj** [comment] 2016-10-31 14:44
+1

**Comment by hasnainshafqatmlt** [comment] 2017-04-08 12:20
Hi 
no one give the answer is that possible to set Datepicker inline or not ?

**Comment by the-codery** [comment] 2017-06-15 16:32
Does anyone have an example of how they implemented this?

**Comment by chiwiu** [comment] 2017-07-20 13:55
To implement an inline datepicker as seen in the [Table component](http://react-toolbox.com/#/components/table):
`
<input
          onChange={onChangeFunction)}
          type='date'
          value={inputValue}
        /> 
 `

I took that from the react-toolbox Table component code, you can see it more in detail in line 92 of the following file in the version 1.3 of the library: [TableRow.js](https://github.com/react-toolbox/react-toolbox/blob/master/components/table/TableRow.js)

**Comment by the-codery** [comment] 2017-07-20 13:59
That just a date input field. It isn't the same as inlining the `DatePicker` component.

**Comment by kamalchaturvedi15** [comment] 2018-01-08 09:13
Is this closed ? I believe there is still no way we can inline the Datepicker provided by react-toolbox. @javivelasco Do you plan to bring this up in the near future ?

**Comment by pietrofxq** [comment] 2018-01-18 02:19
+1, I'm planning to use it but the calendar inside the dialog is a deal breaker for me.
