### ISSUE TITLE
Should use module request instead of loader config

### ISSUE THREAD

**Issue by sonhanguyen** [react-toolbox/react-toolbox#675] opened 2016-07-27 23:29 UTC
I've had a problem similar to #207, which brings me to questioning _react-toolbox_ assuming certain webpack configs such as `css?modules`.
Currently the way I've solved this is adding a line in my `webpack.config.js` just for _react-toolbox_
```js
      { loader: 'style!css!sass', test: /\.scss$/, exclude: /react-toolbox/ },
      // react-toolbox assumes this config in order to work
      { loader: 'style!css?modules!sass', test: /\.scss$/, include: /react-toolbox/ },
```
The fact that users have to be aware that _react-toolbox_ uses _css-modules_ like this is a leaky abstraction. IMHO a more portable implementation will let user `import <component>` that just works without further config. Webpack has **module request** to provide this encapsulation but for some reason libraries still abuse the config.

**Comment by javivelasco** [comment] 2016-08-06 17:58
Hi @sonhanguyen!

To my knowledge using css-modules and css-loader it's not the same thing. You can allow the user to require CSS files just with an `import` statement that resolves to nothing and the CSS will be bundled in the output. That solves one problem, but your CSS would not be scoped though. You would need to manually add `string` classNames to your rendered HTML.

In the [README](https://github.com/webpack/css-loader#css-modules) from css-loader you can see that to enable CSS Modules mode you need to pass `modules` option to the loader query string to enable the [CSS Modules spec](https://github.com/css-modules/css-modules). So when we say *React Toolbox uses css-modules* we are speaking about the spec.

Also, you have to keep in mind that our components implement a `className` API that is based on CSS Modules. You can import components raw but you need to still provide a `theme` object with the appropriated classNames, just as css-modules import resolves to.

If we allow just to require a component bundling styles we are forcing everybody to use and configure CSS Modules. Currently there is no need to do it because you are free in import the component factory and inject an fake CSS Module with the className mapping you want.

But, of course, if you want to require and use a component with a single `import` you have to enable CSS Modules. Maybe I'm missing something but I don't see what would give module request over this.

**Comment by sonhanguyen** [comment] 2016-08-06 20:28
I guess I didn't make my point clear enough. It IS great that _react-toolbox_ uses _css-modules_, but to me it doesn't feel right when you change the default behavior. The default one is to have scoped style you need to explicitly use `:local`. With the `modules` option on, everything will be scoped.

For people have css-loader in their config and don't even know about css-modules or opt not to use it, or use `:local` when appropriate like I do, they have to either modify their webpack config like I did or change all their code to implicit `:local` and explicit `:global`.

However changing _react-toolbox_ code to _css-modules_'s default won't help since that would conflict with people who already have css?modules in their config.

I suggested **module request** because with it you can have the library loader queries independent from the consumer's config, that way users are not even required to have _sass_ in their webpack setup.

Hope that makes sense.

**Comment by javivelasco** [comment] 2016-08-06 20:47
Oh I see. The problem is that we would be coupled to webpack. Right now if your module can request a css module, react-toolbox would work. It doesn't matter if it's webpack or anything else. I don't know if that syntax is present in other module bundlers like JSPM. If so, it is not coupled to webpack and it would make sense I think

**Comment by sonhanguyen** [comment] 2016-08-06 21:21
Thanks, I saw the issue regarding the `!sass` loader in jspm and assumed the syntax available. Couldn't find any regarding docs but now that I think about it, it seems not likely, especially in things like browserify or rollup.

How viable it is to change from `import` to `require` internally just for style, so that we can detect bundler and request accordingly?

**Comment by javivelasco** [comment] 2016-08-07 12:26
I think that if we change from import to require we are missing some good parts that comes with ES6 imports. We are relying hardly on its implementation if you check how are dependencies exposed from the source files and `index.js` files. Of course we could change it but it also would be less verbose.

Anyway, I agree it would be could to configure automatically from the module request if we detect you are using webpack but that would also assume that you have already installed css-loader. Or, we can add css-loader as a peer dependency in the project which I don't like either because it requires a peer from webpack. It's not good for server side rendering either...

The most pragmatic solution in my opinion is to keep relying on user configuration. If you are more or less familiar with it, it shouldn't be difficult. Still be need to provide a [better documentation](https://github.com/react-toolbox/react-toolbox/issues/673) to help people configuring webpack of whatever module bundler they are using. I'm closing this but feel free to reopen if you figure out a way that works better for you without too many side effects :)

**Closed by javivelasco** 2016-08-07 12:26 UTC
Labels: question
