### ISSUE TITLE
Load style without breaking current global css/scss

### ISSUE THREAD

**Issue by Agowan** [react-toolbox/react-toolbox#121] opened 2015-11-17 13:45 UTC
I'm trying to get react-toolbox running in our new project of ours.
The problem I'm facing is that my required scss files will act as global and not "namespaced" for each component.

When I'm trying to make the style load for react-toolbox, I get it to work but in the progress I'm breaking our current scss. And of course when I revert my loaders to the original state, the style breaks for my react-toolbox element (Dropdown).

*Global scss working, react-toolbox style broken*
```javascript
test    :  /(\.scss|\.css)$/,
loaders : [
  'style-loader',
  'css-loader',
  'sass-loader?includePaths[]=' + paths.src('styles')
]
```

*Global scss broken, react-toolbox style working*
```javascript
test    :  /(\.scss|\.css)$/,
loaders: [
  require.resolve('style-loader'),
  require.resolve('css-loader') + '?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]',
  require.resolve('sass-loader') + '?sourceMap'
]
```

Is there a way of loading the style for each component and keep my own required scss global?

**Comment by javivelasco** [comment] 2015-11-17 14:45
Hi @Agowan! 

By default we are including some global styles and `normalize.css`. This is because we are using `rems` as base unit and this way we are not forcing the user to reset and stuff. If you want to include React Toolbox in a running project without applying any global styles, I think we can use a variable to accomplish it.

I'm going to keep the issue open and labeled as bug. This afternoon I can release a new version supporting a variable in your configuration stylesheet to avoid loading global styles. I'll update then.

**Comment by Agowan** [comment] 2015-11-17 16:05
Hi,
thanks for quick reply.
I might have misunderstood you answer but I want react-toolbox to be namespaced for it's own components and keep my own style global.
If I remove the `sourceMap&modules` from the `loaders` my style/css works but react toolbox dropdown look like this:

![screenshot 2015-11-17 16 42 03](https://cloud.githubusercontent.com/assets/239752/11216199/38438374-8d4a-11e5-8aa0-e6837360817a.png)

This is the code I'm using:
```javascript
...
render() {
  const pageSizes = [
    {label: '10', value: 10}, 
    {label: '10', value: 10}, 
    {label: '20', value: 20}, 
    {label: '50', value: 50}, 
    {label: '100', value: 100}
  ];
  return (<Dropdown auto onChange={this.onChange.bind(this)} source={pageSizes} />);
}
...
```
And if I add it again, my previously global (working) css classes becomes namespaced and thus my global classes wont be recognised. But the style for react toolbox dropdown gets recognised and looks like this (better then previous)

![screenshot 2015-11-17 17 02 35](https://cloud.githubusercontent.com/assets/239752/11216724/0d02048a-8d4d-11e5-93e2-a5834c0cf5c4.png)



But you might have a point in not loading any global styles, that might be a problem as well.

**Comment by javivelasco** [comment] 2015-11-17 16:57
Sorry if I'm not explaining myself well enough. React Toolbox provides components with all style namespaced so they are not going to collide with your external styles. This is how it's built and it's the main purpose of the library.

Apart from that, we have a module with global CSS to provide an easy way to bootstrap your a project. [This](https://github.com/react-toolbox/react-toolbox/blob/master/components/commons.scss) is the file that sets global styles for your page. The main reason is to reset html nodes, to add normalize, load `Roboto` font, etc, but you don't have to load the file if you are already reseting your stylesheet.

If you want to use components isolated you have to make sure you are adding the reset rules. For example, we are not resetting each `ul` tag element in each component that uses an `ul`, we are resetting them **globally**. If you don't include this globals you have to change a bit these resets to make components look nice. Anyway, this resetting should be included *only* if you import `commons.scss` manually. If you just add toolbox and import the `Dropdown` it's going to load only the styling for the dropdown but, again, you have to reset the list yourself. Doing the reset in each component is a violation of DRY and would make the css grow.

Feel free to ping me through Discord if you want to discuss further or need help. As soon as I make sure the globals are not imported when using a component alone I'm closing the issue.

Thanks!

**Comment by javivelasco** [comment] 2015-11-17 16:57
Also, remember you are responsible from loading the CSS with CSS modules providing a hashed name and avoiding collisions!

**Comment by javivelasco** [comment] 2015-11-18 23:53
Now we have commons out of `App` component. This means you are able to use Toolbox and the wrapper without requiring the `commons` we were adding. Also, we added some configuration variables that will be in the documentation for the next release:

- `$import-normalize`
- `$import-font`
- `$import-flex-attributes`

Now to include the commons in your project you have to do it manually: `@import "~react-toolbox/lib/commons"`. Still, if you don't want to use them, you'd have to reset lists, change underlines for anchors, and set the `$unit` size or base `rem` yourself.

Please check it from master. Coming in next release!

**Closed by javivelasco** 2015-11-18 23:53 UTC
Labels: bug

**Comment by mattgi** [comment] 2015-12-05 23:37
@javivelasco i think this is the same issue i am facing but the issue is actually more that all existing styling in an app is broken unless it conforms to CSS modules. I believe there should be a way to limit the loaders to just react-toolbox but I am not sure how - any ideas?

Consider an app that is currently using bootstrap (or equiv.) with a simple `import 'styles/index.scss';` in its `index.js`. So, within components, they just assume styles like `container` and `row` to exist. `<div className="container" />`. When you pull in react-toolbox (and change webpack to work with react-toolbox) it breaks all default styling - as `.container` no longer exists (instead has to be renamed to `.index__container___xxxxx`) so that react-toolbox can find its styles.

This seems like a pretty intrusive approach - basically, to use react-toolbox, you have to also take on the modular approach to CSS. Whilst this approach does look like an awesome solution to styling react projects, its often unrealistic to rewrite an entire app if it would like to utilize react-toolbox.

Any ideas on how it could work without have to rewrite everything?

**Comment by mattgi** [comment] 2015-12-05 23:59
so, something like this will work:

```
      {
        test    : /(\.scss|\.css)$/,
        include : path.join(__dirname, '../../', 'src'),
        loaders: [ 'style', 'css', 'sass' ]
      },
      {
        test    : /(\.scss|\.css)$/,
        exclude : path.join(__dirname, '../../', 'src'),
        loaders: [
          require.resolve('style-loader'),
          require.resolve('css-loader') + '?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]',
          require.resolve('sass-loader') + '?sourceMap',
          'toolbox'
        ]
      },
      {
        test: /\.(png|woff|woff2|eot|ttf|svg)$/,
        loader: 'url-loader?limit=100000'
      }
```

Feels like an anti-pattern putting a dependency's compilation step into an app's webpack though.

**Comment by mattgi** [comment] 2015-12-06 00:11
I should add that this set up still allows you to utilize toolbox and provide your own theme... which is very cool.

**Comment by javivelasco** [comment] 2015-12-06 10:43
Hi @mattgi thanks for you feedback! I think there are multiple things to consider here. First of all, I think there is no way to avoid including css modules in your project to use it with react toolbox. If you still want to keep some global styles for bootstrap I think there are multiple choices: 

- If you want to keep global styles coming from bootstrap, I think the best way would be to specify in Bootstrap CSS that it should be `:global`. Since it's sass, you can just include what you need in an `@include` file wrapped with `:global` or just put it in bootstrap source.

- You can tell webpack it should only use css modules for files placed at react toolbox module directory. This can be achieved by modifying the test for your loader. Just put only React Toolbox css into the loader.

The problem with globals is that now we have a general commons file that makes a reset and some other styling project-wide. The thing is that we did it this way to avoid repeating resets for lists for example. Anyway there is a way to still avoid repeating ourselves and get the reset for each module with a local scope. It's coming in next version.

Hope you can configure it properly, cheers!

**Comment by victornguyen** [comment] 2015-12-10 04:29
>Also, we added some configuration variables that will be in the documentation for the next release:
>
>* `$import-normalize`
>* `$import-font`
>* `$import-flex-attributes`

Hey @javivelasco, are these vars available in a current release?

I can't seem to find them in `0.13.4`?

**Comment by javivelasco** [comment] 2015-12-10 08:50
Hi @victornguyen !

We removed `$import-font` because now you are responsible from loading the font, it's not the best practice to perform vendor imports from the CSS. Also, `$import-flex-attributes` was removed along with it's dependencies. About `$import-normalize`... apparently I removed it for no reason, I'll restore it for the next release.

Check out the changelog for more information about the font loading.
Thanks!

**Comment by JeroenNelen** [comment] 2016-06-24 13:10
@mattgi thanks for the info, it indeed allows to still set a custom theme. However, overwriting specific components seems troublesome as for passing a theme to a component, it is required to be a CSS module. Does anyone has any suggestion for doing that differently?

**Comment by JeroenNelen** [comment] 2016-06-24 13:17
I notice I can still add a className and set properties that way, but probably only if they are not yet set in the react-toolbox's scss? 
E.g. I set the width on a button in my own, non-module, scss and pass the class via className on to <Button... is this troublesome?

**Comment by malexanders** [comment] 2016-06-24 19:32
I having a hell of a time with similar problem - no luck so far. I realize this issue is closed - Is it possible for someone to give me a hand?

**Comment by javivelasco** [comment] 2016-06-25 10:40
May you expose your issue again? In the previous version you needed to support CSS Modules because importing a react-toolbox component implied to import a css module. With the 1.0 version you don't need it anymore because you can import components RAW without any CSS and then inject a theme via props or context. Considering that a theme is nothing but an object matching className in the API - real css class to apply styles, you can configure following this options:

1 - Without CSS modules: import always raw components and provide a theme to theme. You can either create wrapper components inject styles or to give a context theme object with the theme for each component. The provided theme should be created by yourself or compiled on your own from our SASS files. We don't have an example on this yet but it's quite straightforward. This is intended for people not using CSS Modules.

2 - Via variables: each component imports some variables that can be overridden. You can do so using injecting for custom variables at the beginning of each SASS compile. To achieve it you can use toolbox-loader or a sass-loader option for webpack. Just create a file with your variables override and tell your bundler to inject that file. This is for people that want to override styles widely without messing with CSS and are in fact using CSS modules.

3 - Via themes: You can also import themed components and provide a theme object. The classes you provide in that object will be mixed with the given by react toolbox meaning that adding a className to your component you can combine both in your CSS to override styles with more priority. This last one is the easiest for people who want to customize a component but use the default ones and use CSS modules.

Good luck!

**Comment by JeroenNelen** [comment] 2016-06-25 14:33
hello @javivelasco,

Thanks for your information. I am, however, still struggling with getting it to work as expected, most likely because I am using it with webpack and typescript. To answer your suggestions:
1) This seems to not work with typescript anyway because when trying 
`import { Button } from 'react-toolbox/lib/button';` 
I get a typescript error that there is no such module: `error TS2307: Cannot find module 'react-toolbox/lib/button/Button.js'.`
And wouldn't it still require to use CSS modules as we would have to pass a theme to the theme parameter and the theme parameter expects a CSS module?

2) This seems to work with my current setup (tried overriding the primary color), however this is no option for 'page-specific' adjustments, e.g. on one page I want the button to have a 30px height and on another page it should have a 50px height (fictive example, overriding style attributes differently on several pages).

3) I am currently using require to get the CSS module: `let buttonStyles = require('./theme');`
- when I pass buttonStyles to theme={} the typescript compiler also complains because the theme parameter is not defined in the react-toolbox's typings button/index.d.ts (so I just added theme: any to test it)
- if I don't use require, typescript would complain as there are no typings available for the CSS module
- it also seems that the file name is used to define the selector, so e.g. I want to override the height in the button, if I inspect the button the height property is set under `.theme__raised___1CNoR`, so I had to name the scss file with the button customisation 'theme' in order to get a .theme__raised selector, however I end up with a different hash: `.theme__raised___35sY-`, which also gets overriden by the one from react-toolbox itself (so my customisation doesn't get through). 
If this would work, then it seems troublesome that the file name has to be theme.scss for the customisations? For example when I have a page on which I want to customise a Button but also an App-bar, then I have to place both customisations in the same theme.scss file? But then the button  styling would also be present on the appbar and vice versa?

Am I overlooking something or do you have any suggestions/ideas in what direction I can move to get any of the 3 to work? If something about my explanation isn't clear, please let me know!

I really want to get it to work because I would prefer using this library over material-UI (I prefer the separate .scss files for styling in stead of the inline styling).

Kind regards,

**Comment by malexanders** [comment] 2016-06-25 21:00
I managed to get mine working, have a look at my package.json and webpack.config. Let me know if you have any questions:

package.json

```
{
  "name": "pluralsight-redux-starter",
  "version": "1.0.0",
  "description": "Starter kit for React and Redux Pluralsight course by Cory House",
  "author": "Cory House",
  "license": "MIT",
  "//": "alternative for this include gulp and grunt",
  "scripts": {
    "//": "react specific library, you can use redux with other libraries as well, like angular etc...",
    "prestart": "babel-node tools/startMessage.js",
    "start": "npm-run-all --parallel open:src lint:watch test:watch",
    "open:src": "babel-node tools/srcServer.js",
    "lint": "node_modules/.bin/esw webpack.config.* src tools",
    "lint:watch": "npm run lint -- --watch",
    "test": "mocha --require ignore-styles --reporter spec tools/testSetup.js \"src/**/*.test.js\"",
    "test:watch": "npm run test -- --watch",
    "clean-dist": "npm run remove-dist && mkdir dist",
    "prebuild": "npm-run-all clean-dist test link build:html",
    "build": "babel-node tools/build.js",
    "postbuild": "babel-node tools/distServer.js"
  },
  "dependencies": {
    "babel-polyfill": "6.8.0",
    "bootstrap": "3.3.6",
    "css-loader": "^0.23.1",
    "jquery": "2.2.3",
    "minimatch": "^3.0.2",
    "node-sass": "^3.8.0",
    "react": "15.1.0",
    "react-dom": "15.0.2",
    "react-redux": "4.4.5",
    "react-router": "2.4.0",
    "react-router-redux": "4.0.4",
    "react-toolbox": "^1.0.1",
    "redux": "3.5.2",
    "redux-thunk": "2.0.1",
    "resolve-path-webpack-plugin": "^1.1.0",
    "sass-loader": "^3.2.1",
    "style-loader": "^0.13.1",
    "toastr": "2.1.2",
    "webpack-validator": "^2.2.0"
  },
  "devDependencies": {
    "babel-cli": "6.8.0",
    "babel-core": "6.8.0",
    "babel-loader": "6.2.4",
    "babel-plugin-react-display-name": "2.0.0",
    "babel-preset-es2015": "6.6.0",
    "babel-preset-react": "6.5.0",
    "babel-preset-react-hmre": "1.1.1",
    "babel-register": "6.8.0",
    "colors": "1.1.2",
    "compression": "1.6.1",
    "cross-env": "1.0.7",
    "css-loader": "0.23.1",
    "enzyme": "2.2.0",
    "eslint": "2.9.0",
    "eslint-plugin-import": "1.6.1",
    "eslint-plugin-react": "5.0.1",
    "eslint-watch": "2.1.11",
    "eventsource-polyfill": "0.9.6",
    "expect": "1.19.0",
    "express": "4.13.4",
    "extract-text-webpack-plugin": "1.0.1",
    "file-loader": "0.8.5",
    "ignore-styles": "^4.0.0",
    "jsdom": "8.5.0",
    "mocha": "2.4.5",
    "nock": "8.0.0",
    "normalize.css": "^4.0.0",
    "npm-run-all": "1.8.0",
    "open": "0.0.5",
    "postcss-loader": "0.8.2",
    "react": "^15.0.2",
    "react-addons-css-transition-group": "^15.0.0",
    "react-addons-test-utils": "15.0.2",
    "redux-immutable-state-invariant": "1.2.3",
    "redux-mock-store": "1.0.2",
    "rimraf": "2.5.2",
    "sass-loader": "^3.2.0",
    "style-loader": "0.13.1",
    "toolbox-loader": "0.0.3",
    "url-loader": "0.5.7",
    "webpack": "1.13.0",
    "webpack-dev-middleware": "1.6.1",
    "webpack-hot-middleware": "2.10.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/coryhouse/pluralsight-redux-starter"
  }
}
```

webpack.config
```

import webpack from 'webpack';
import path from 'path';
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const modulesPath = path.join(__dirname, 'node_modules');
const autoprefixer = require('autoprefixer');

  export default {
      debug: true,
      devtool: 'source-map',
      noInfo: false,
      entry: [
          'eventsource-polyfill', // necessary for hot reloading with IE
          'webpack-hot-middleware/client?reload=true', //note that it reloads the page if hot module reloading fails.
          './src/index.js'
      ],
      target: 'web',
      output: {
          path: __dirname + '/dist', // Note: Physical files are only output by the production build task `npm run build`.
          publicPath: '/',
          filename: 'bundle.js'
      },
      devServer: {
          contentBase: './src'
      },
      plugins: [
          new webpack.HotModuleReplacementPlugin(),
          new webpack.NoErrorsPlugin()

      ],
      resolve: {
        extensions: ['', '.css', '.scss', '.js', '.json'],
        modulesDirectories: ['node_modules']
      },
      postcss: [autoprefixer],

      toolbox: {
        theme: path.join(__dirname, 'src/styles/variables.scss')
      },
      // Tells webpack the types of files that we want it to handle.
      module: {
          loaders: [
              {test: /(\.js|\.jsx)$/,
                include: path.join(__dirname, 'src'),
                loaders: ['babel']
              },
              {
                test: /\.s?css$/,
                loaders: ['style', 'css', 'sass'],
                exclude: /(node_modules)\/react-toolbox/
              },
              {
                test    : /(\.scss|\.css)$/,
                include : /(node_modules)\/react-toolbox/,
                loaders : [
                  require.resolve('style-loader'),
                  require.resolve('css-loader') + '?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]',
                  require.resolve('sass-loader') + '?sourceMap', 'toolbox'
                ]
              },
              {test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: 'file'},
              {test: /\.(woff|woff2)$/, loader: 'url?prefix=font/&limit=5000'},
              {test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=application/octet-stream'},
              {test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=image/svg+xml'}
          ]

      }
  };
```

**Comment by JeroenNelen** [comment] 2016-06-26 10:42
hello @malexanders, 

I have the general setup working as well, but as I mentioned I am currently not able to over-write the styling (apart from the general theme) for specific components. 
Either I am overlooking something or maybe it is just not possible with the Typescript setup. 
I hope @javivelasco has an idea or suggestion.

Kind regards,

**Comment by giacomorebonato** [comment] 2016-07-17 08:40
I am using react-toolbox in an empty project.
I have rendered the **AppBar** and I have noticed two things.
- The body still has margins, so I added normalize.css... just for precautions
- My app bar height is bigger compared to the one of React-Toolbox site

![toolbox](https://cloud.githubusercontent.com/assets/630796/16899612/22c590c4-4c02-11e6-8793-5dbd8b62bd02.png)

It is because the toolbox site has font-size: 62.5% on the html element.
Why am I missing these settings?

**Comment by javivelasco** [comment] 2016-07-17 20:25
You have to import a `commons.scss` stylesheet that includes a reset and some base settings that are used in react-toolbox :)

**Comment by giacomorebonato** [comment] 2016-07-18 09:34
Now everything looks at expected. Where did I miss this key configuration's instruction?
I don't know if matters... but I am using Typescript with Webpack and now I am importing commons.scss into my global.scss

**Comment by javivelasco** [comment] 2016-07-18 10:32
Yeah, it's missing. We should add it :/

**Comment by warent** [comment] 2016-07-20 19:12
@malexanders That did the trick, thank you!

**Comment by Findiglay** [comment] 2016-09-08 12:06
@JeroenNelen Can you confirm whether you ever found a solution to this? I'd like to use react-toolbox in a project but a requirement is that someone who only knows css should be able to write and bundle in some of their own overrides. However, if the themed classname hash changes on each compile, this may be a deal-breaker.

**Comment by JeroenNelen** [comment] 2016-09-19 15:08
@Findiglay sorry for my late reply, I'm currently no longer working with this library so unfortunately I can't offer you any advice/solution on this.

kind regards,

**Comment by danmolitor** [comment] 2016-10-20 23:07
Hey all, I've pretty much followed @malexanders webpack config to be able to both use bootstrap, my own custom scss and react-toolbox, however i'm getting an error like this for each component theme file in the lib folder: 

`ERROR in ./~/css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/sass-loader?sourceMap!./~/toolbox-loader!./~/react-toolbox/lib/button/theme.scss
Module build failed: Error: ENOENT: no such file or directory, open '/Users/dm/Documents/programming/ll/theme.scss'
    at Error (native)
 @ ./~/react-toolbox/lib/button/theme.scss 4:14-230 13:2-17:4 14:20-236`

My webpack config is: 

`
let webpack = require('webpack');
let HtmlWebpackPlugin = require('html-webpack-plugin');
let ExtractTextPlugin = require('extract-text-webpack-plugin');
const path = require('path');
const autoprefixer = require('autoprefixer');
const modulesPath = path.join(__dirname, 'node_modules');

let HtmlWebpackPluginConfig = new HtmlWebpackPlugin({
  template: __dirname + '/app/index.html',
  filename: 'index.html',
  inject: 'body'
});

let WebpackEnvPlugin = new webpack.DefinePlugin({
  'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development'),
  // RETHINK_HOST: JSON.stringify(process.env.RETHINK_HOST),
  PORT: JSON.stringify(process.env.PORT)
});

module.exports = {
  devtool: 'source-map',
  entry: [
  'webpack-hot-middleware/client?reload=true',
  './app/index.js'
  ],
  output: {
    path: __dirname + '/dist',
    filename: 'index_bundle.js',
    publicPath: '/assets'
  },
  resolve: {
    extensions: ['', '.css', '.scss', '.js', '.json'],
    modulesDirectories: ['node_modules']
  },
  postcss: [autoprefixer],
  module: {
    loaders: [
      {
        test: /(\.js)$/,
        loaders: ['babel']
      },
      {
        test: /\.s?css$/,
        loaders: ['style', 'css', 'sass'],
        exclude: /(node_modules)\/react-toolbox/
      },
      {
        test    : /(\.scss|\.css)$/,
        include : /(node_modules)\/react-toolbox/,
        loaders : [
          require.resolve('style-loader'),
          require.resolve('css-loader') + '?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]',
          require.resolve('sass-loader') + '?sourceMap', 'toolbox'
        ]
      },
      {
        test: /\.(jpe?g|png|gif|svg)$/i,
        loaders: [
            'file?hash=sha512&digest=hex&name=[hash].[ext]',
            'image-webpack?bypassOnDebug&optimizationLevel=7&interlaced=false'
        ]
      }
    ]
  },
  plugins: [
  HtmlWebpackPluginConfig,
  WebpackEnvPlugin,
  new ExtractTextPlugin('css/main.css', {
            allChunks: true
        }),
  new webpack.optimize.OccurenceOrderPlugin(),
  new webpack.HotModuleReplacementPlugin()
  ]
}
`

If you had any input on what I'm doing wrong or overlooking that'd be much appreciated!
