### ISSUE TITLE
Dropdown onChange event not firing on source select

### ISSUE THREAD

**Issue by danieljodeci** [react-toolbox/react-toolbox#1459] opened 2017-05-13 21:15 UTC
I'm having a strange issue where the onChange property for the Dropdown component won't trigger any events. I'm using the example from the website and using react-toolbox@2.0.0-beta.8 
```import Dropdown from 'react-toolbox/lib/dropdown';

const countries = [
  { value: 'EN-gb', label: 'England' },
  { value: 'ES-es', label: 'Spain'},
  { value: 'TH-th', label: 'Thailand' },
  { value: 'EN-en', label: 'USA'}
];

export default class DropdownTest extends React.Component {
  state = { value: 'ES-es' };

  handleChange = (value) => {
    console.log('please work:', value);
    this.setState({value: value});
  };

  render () {
    return (
      <Dropdown
        auto
        onChange={this.handleChange}
        source={countries}
        value={this.state.value}
      />
    );
  }
}
```

onBlur works fine. looking deeper it seems the onClick event attached the the 'li' element isn't firing the handleSelect function.

**Comment by brandonfajardo** [comment] 2017-05-24 14:01
I'm having the same problem, any suggestions?

**Comment by mbilokonsky** [comment] 2017-06-01 20:41
Can confirm that I'm having the same problem as well. Anyone found a solution?

**Comment by danieljodeci** [comment] 2017-06-01 23:57
i wasn't able to find a solution. ended up using react-select and customizing the styling to match react-toolbox. annoying but worked out. still am curious as to a solution for this issue.

**Comment by joelzimmer** [comment] 2017-06-07 13:59
Hey all - we have a fix for this pending that we would love anyone to look at - can someone do that?

**Comment by joelzimmer** [comment] 2017-06-09 20:23
@javivelasco @soyjavi Hey guys, we'd love if you could take a look at this.

**Comment by mbilokonsky** [comment] 2017-06-09 20:33
If this works, I'd LOVE a merge and bugfix version bump sooner than later...

**Comment by tobiasandersen** [comment] 2017-06-21 09:42
Hm, I'm unable to reproduce this. If someone seeing this could create a minimal reproducible example, it would be really helpful. I'm not sure about replacing `onClick` with `onMouseDown` (as proposed in #1521), it feels more like a hack.

**Closed** 2017-08-02 16:27 UTC
