### ISSUE TITLE
react-toolbox domain is down (http://react-toolbox.com/)

### ISSUE THREAD

**Issue by deSargeSoftware** [react-toolbox/react-toolbox#1734] opened 2017-11-01 09:20 UTC
http://react-toolbox.com/ is down: This Domain Name Has Expired. Could you please renew it :)? Thanks

**Comment by vampxlr** [comment] 2017-11-01 09:55
Eagerly waiting for it to come up live again.

**Comment by roadev** [comment] 2017-11-01 15:02
It will be awesome if you move to Github Pages.

**Comment by deSargeSoftware** [comment] 2017-11-01 17:20
Until is up, you can use this one: https://peddler-jam-26368.netlify.com/#/ (I received as well).

**Comment by neoromantic** [comment] 2017-11-02 00:55
Funny that how that is happening every year :)

**Comment by drunkengranite** [comment] 2017-11-02 02:02
bump

**Comment by mgcrea** [comment] 2017-11-03 14:28
Duplicate of #1731

**Comment by javivelasco** [comment] 2017-11-13 20:21
react-toolbox.io is up now!

**Closed by javivelasco** 2017-11-13 20:21 UTC

**Comment by CASandmann** [comment] 2017-11-15 19:26
Why did you guys switch to a .io domain?  Not that it really matters in the long run, but all old links to the docs are now broken and the new location doesn't show up on a Google search while the old (broken) one still does.

**Comment by javivelasco** [comment] 2017-11-15 22:27
Because @soyjavi has ownership of the `.com` and it was impossible to reach him or to make him renew the domain so I had to switch to keep ownership of the whole thing. The docs and everything will be updated during the next days, sorry about it
