### ISSUE TITLE
"Module build failed"

### ISSUE THREAD

**Issue by amensouissi** [react-toolbox/react-toolbox#466] opened 2016-04-21 11:08 UTC
Hello,
I get this error when try to start the project...

npm install
npm start
...
Child extract-text-webpack-plugin:
    
    ERROR in ./~/css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./~/sass-loader?sourceMap!./components/snackbar/style.scss
    Module build failed: 
      @import "./colors";
     ^
          Import directives may not be used within control directives or mixins.
          in /home/amensouissi/workspace_react/react-toolbox/components/_base.scss (line 4, column 3)
....

**Comment by digipi** [comment] 2016-04-21 12:16
Having the same issue. I'm using the react-redux-starter-lot by Dave Zuko. Any ideas?

**Comment by vincentfretin** [comment] 2016-04-21 12:16
removing the if in _base.scss and just having
````
@import "./colors";
@import "./globals";
@import "./mixins";
```
fixes the issue.

**Comment by amensouissi** [comment] 2016-04-21 12:17
#451

**Comment by dlebedynskyi** [comment] 2016-04-21 18:05
can you please make patch release for this? CI is going nuts due to this error

**Comment by nickretallack** [comment] 2016-04-21 20:38
Yeah, it'd be nice to have a working package that can be installed without modification.  Could you resolve this somehow?

You could apply this change to core, though I'm not sure how you'd reconcile this with your theming system.

Or, you could specify a version dependency for sass that prevents it from upgrading to the version that breaks it.

**Comment by nickretallack** [comment] 2016-04-21 20:53
Oh, huh, it is specified to use 3.4.2 but it still breaks for me.  Perhaps it's a dependency of a dependency that is at fault.

**Comment by dlebedynskyi** [comment] 2016-04-21 23:10
note this 
https://github.com/sass/node-sass/issues/1459#issuecomment-212839565

this is a bug. won't fix. might need to fix lib  here in first place to be compatible

**Comment by nickretallack** [comment] 2016-04-21 23:45
There's a few other syntax errors too, it seems, at least [as far as the linter is concerned](https://travis-ci.org/react-toolbox/react-toolbox/builds/124861860).  I'm not sure what's wrong with these lines, though.

It complains about [this](https://github.com/react-toolbox/react-toolbox/blob/dev/components/date_picker/style.scss#L52), [this](https://github.com/react-toolbox/react-toolbox/blob/dev/components/input/style.scss#L43), [this](https://github.com/react-toolbox/react-toolbox/blob/dev/components/input/style.scss#L143), [this](https://github.com/react-toolbox/react-toolbox/blob/dev/components/list/style.scss#L64), [this](https://github.com/react-toolbox/react-toolbox/blob/dev/components/slider/style.scss#L94)...  a lot of places.

**Comment by mattkauffman23** [comment] 2016-04-22 16:29
@nickretallack I was able to work around this by pinning my peer dependency on node-sass to 3.4.2.

**Comment by nickretallack** [comment] 2016-04-22 22:12
@mattkauffman23 can you describe exactly what you mean by that?

**Comment by nickretallack** [comment] 2016-04-22 22:28
Huh, I see.  This works:

 * clone react-toolbox-example
 * change [this line](https://github.com/react-toolbox/react-toolbox-example/blob/master/package.json#L43) to `"node-sass": "3.4.2",` 
 * npm install && npm start

**Comment by mattkauffman23** [comment] 2016-04-22 22:39
Yeah as you described changing the dependency on node-sass in your package.json to be `3.4.2` instead of `^3.4.2` tells NPM that you want that specific version. The `^` tells NPM to grab the highest minor version that matches. I'm not an expert on NPM's nuances so I usually just delete a module out of node_modules and do another `npm install` when I need to force it to a particular version.

**Comment by jvivs** [comment] 2016-04-23 22:50
I can confirm tests pass after locking the version of `node-sass`

**Comment by dlebedynskyi** [comment] 2016-04-25 15:47
locking version works great for now. problem is that it won't work with any newer version since conditional import are not not supported :(

**Comment by javivelasco** [comment] 2016-04-27 18:10
Yeah we are removing conditional exports for the next release. It was needed for the toolbox loader but it will be needed no longer with a PR I'm gonna do next weekend

**Comment by visvadw** [comment] 2016-05-03 23:37
@dlebedynskyi What do you mean by "conditional import"? Indeed, I got into this issue and `node-sass: 3.4.2` saved me. I am asking this since `react-toolbox/lib/_base.scss` has a conditional import and this setup is working.

See [here](https://github.com/visvadw/react-redux-toolbox-starter) a minimal example, created while trying to have a working HMR setup.

@javivelasco Javi, thank you for this wonderful kit. 👍 
I just started using it and I am hoping that my search for friendly UI kits ends here.

**Comment by dlebedynskyi** [comment] 2016-05-04 16:16
@visvadw  look here 

https://github.com/sass/node-sass/issues/1459#issuecomment-212839565

basically they are saying that 
>Conditional imports are not possible in Sass. 
as a language feature.
it was working as bug in 3.4.2 in SASS lib  and in 4* they when to standard SASS  that caused cases like 
```
if (true) { import .... } 
```
to fail

**Comment by visvadw** [comment] 2016-05-05 17:18
@dlebedynskyi Indeed, it was a useful bug, apparently. Thanks for the details, I overlooked this aforementioned reference to the node-sass issue.
I'm sorry but I don't understand the last statement: the next release of react-toolbox will work with the latest (currently 3.7.0) release of node-sass?

**Comment by dlebedynskyi** [comment] 2016-05-09 17:01
@visvadw  you might ask @javivelasco about that. should be, I hope)

**Comment by javivelasco** [comment] 2016-05-10 18:35
Yeah, @visvadw it will. All dependencies are going to be updated and also a new approach to styling is coming. I'm migrating step by step but it should be ready by the weekend

**Comment by javivelasco** [comment] 2016-05-10 18:46
Also some fixes are done in `dev` so I'm closing! Reopen if there are still issues to solve in the main branch

**Closed by javivelasco** 2016-05-10 18:46 UTC

**Comment by kimrgrey** [comment] 2016-05-18 13:14
Hi, @javivelasco! As you mentioned before this problem has been fixed in dev. Could you please clarify what commit fixes this issue? And what about release? Are you planning it? It's really annoying to lock version of `node-sass` 😞  So, I will be glad to help in any useful way to speed up the next release.

**Comment by javivelasco** [comment] 2016-05-18 16:10
I'm currently working in the update to the themr version. I hope to have it ready for the weekend. Anyway, apart from the themr commits, it should be working in [this branch](https://github.com/react-toolbox/react-toolbox/tree/react-css-themr-migration). From [here](https://github.com/react-toolbox/react-toolbox/commit/91bd684ec6c7ebb6202d9fa91a4106661a667c63) everything should be updated a ready to work!

**Comment by InSuperposition** [comment] 2016-06-10 18:31
I've also run into this same issue with node-sass' problem with Sass imports.

This is an interesting approach to importing styles for CSS modules.
https://github.com/jacobp100/es-css-modules
