### ISSUE TITLE
Dropdown shows disabled

### ISSUE THREAD

**Issue by phumberdroz** [react-toolbox/react-toolbox#1269] opened 2017-02-25 22:51 UTC
Hey People,

I am currently trying out react-toolbox and dropdowns.

Sadly the cursor makes it look like there are disabled.

But when I click the onChange is still kicked off.

https://github.com/phumberdroz/test-react-toolbox/blob/master/client/modules/Post/pages/PostListPage/PostListPage.js#L73-L80

Example:
http://167.114.229.7:8000/ (see console.log when you click)

Anything I might be missing here?

    "react-toolbox-themr": "^1.0.2"
    "react-toolbox": "2.0.0-beta.6"

**Comment by elazzabi** [comment] 2017-02-25 23:35
Hello,

Seeing the error on the console looks like it's a ReactDOM error and not related to react-toolbox. Can you please [try this](http://stackoverflow.com/questions/33521047/warning-react-attempted-to-reuse-markup-in-a-container-but-the-checksum-was-inv) and see if it solves the error

**Comment by phumberdroz** [comment] 2017-02-25 23:38
Will do .. Just give me a second but it that error is due to hot module reloading normally.

**Comment by phumberdroz** [comment] 2017-02-25 23:41
Error is resolved (started it in production mode)..

Still shows like it is disabled.

**Comment by elazzabi** [comment] 2017-02-25 23:52
Looks like you can actually click on them and the dropdown closes when you do so (not for the last item as it's disabled). So I guess this has something to do with some CSS. From the DevTools I can see that "cursor: pointer" is disabled.

Any idea if CSS is changed from another file in your app?

**Comment by phumberdroz** [comment] 2017-02-25 23:56
Disabled all css in the app. Still showing it falsely

**Comment by elazzabi** [comment] 2017-02-26 00:00
This is strange, the [same code](http://react-toolbox.com/#/components/dropdown) works fine here. Maybe missing something.

Hope someone can get what's going on here.

**Comment by phumberdroz** [comment] 2017-02-26 00:01
I know the only thing I am not doing is manipulating the state variable.

**Comment by magnusheino** [comment] 2017-03-01 08:21
I have the same problem as @phumberdroz and is using the same tools.

**Comment by magnusheino** [comment] 2017-03-01 08:24
the ul-element that is parent of the li as this css:

    overflow: hidden;
    padding: 10px;
    position: relative;
    cursor: not-allowed;

**Comment by magnusheino** [comment] 2017-03-01 08:32
@elazzabi http://react-toolbox.com/#/components/dropdown is not using 2.0.0-beta.6, right? Also themr might be the problem?

**Comment by elazzabi** [comment] 2017-03-01 22:17
Looking at the docs [package](https://github.com/react-toolbox/react-toolbox/blob/dev/docs/package.json#L17) it is using themr 1.2.0 and up. Not sure if themr problem, could be a problem in the beta, because the cursor: not-allowed isn't normal and I'm not sure from where it comes...

**Comment by magnusheino** [comment] 2017-03-02 09:47
@elazzabi That is react-css-themr you are referring to, we are using react-toolbox-themr. https://github.com/react-toolbox/react-toolbox-themr

**Comment by elazzabi** [comment] 2017-03-02 11:31
Ah, could be the problem. I'm not sure though...

**Comment by icflorescu** [comment] 2017-03-02 23:11
Same problem. It looks like `react-toolbox-themr` generates this for the `ul`:

    .rt-dropdown-values>* {
        cursor: pointer;
        overflow: hidden;
        padding: 10px;
        position: relative;
        cursor: not-allowed;
    }

**Comment by elazzabi** [comment] 2017-03-02 23:13
Seems like it's a bug and intended to be fixed with the next release. See
https://github.com/react-toolbox/react-toolbox-themr/issues/16

**Comment by phumberdroz** [comment] 2017-03-02 23:20
Thanks for the info. I did only check here. :/

**Comment by javivelasco** [comment] 2017-03-15 20:05
Released I think!

**Closed by javivelasco** 2017-03-15 20:05 UTC

**Comment by magnusheino** [comment] 2017-03-15 20:08
@javivelasco what is released? not react-toolbox-themr although react-toolbox/react-toolbox-themr#16 is resolved.

**Comment by magnusheino** [comment] 2017-03-16 08:47
Confirmed. Works now.
